pFoF: modsortinterf Module Reference
modsortinterf Module Reference
This module contains sort subroutines.
Data Types
interface heapsort
Generic inteface used to sort arrays with heapsort algorithm.
interface quicksort
Generic inteface used to sort arrays with quicksort algorithm.
Private Member Functions
recursive subroutine quicksort_refi_2x3r_1xi (p, r, tref, tx, tv, tid)
Quicksort algorith as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
recursive subroutine quicksort_refi_2x3r_1xr_1xi (p, r, tref, tx, tv, tp, tid)
Quicksort algorith as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
recursive subroutine quicksort_refi_3x3r_1xr_1xi (p, r, tref, tx, tv, tf, tp, tid)
Quicksort algorith as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
recursive subroutine quicksort_refi_3x3r_1xi (p, r, tref, tx, tv, tf, tid)
Quicksort algorith as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
subroutine partition_refi_2x3r_1xi (p, r, q, tref, tx, tv, tid)
Partition function for quicksort.
subroutine partition_refi_2x3r_1xr_1xi (p, r, q, tref, tx, tv, tp, tid)
Partition function for quicksort.
subroutine partition_refi_3x3r_1xr_1xi (p, r, q, tref, tx, tv, tf, tp, tid)
Partition function for quicksort.
subroutine partition_refi_3x3r_1xi (p, r, q, tref, tx, tv, tf, tid)
Partition function for quicksort.
subroutine heapsort_refi_2x3r_1xr_1xi (n, tref, tx, tv, tp, tid)
Heap sort as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
subroutine heapify_refi_2x3r_1xr_1xi (size, n, tref, tx, tv, tp, tid)
Heapify routine for heapsort.
recursive subroutine sink_refi_2x3r_1xr_1xi (size, i, tref, tx, tv, tp, tid)
Sink routine for heapsort.
subroutine swap_refi_2x3r_1xr_1xi (i, j, tref, tx, tv, tp, tid)
Swap routine for heapsort.
subroutine heapsort_refi_2x3r_1xi (n, tref, tx, tv, tid)
Heap sort as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
subroutine heapify_refi_2x3r_1xi (size, n, tref, tx, tv, tid)
Heapify routine for heapsort.
recursive subroutine sink_refi_2x3r_1xi (size, i, tref, tx, tv, tid)
Sink routine for heapsort.
subroutine swap_refi_2x3r_1xi (i, j, tref, tx, tv, tid)
Swap routine for heapsort.
subroutine heapsort_refi_3x3r_1xr_1xi (n, tref, tx, tv, tf, tp, tid)
Heap sort as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
subroutine heapify_refi_3x3r_1xr_1xi (size, n, tref, tx, tv, tf, tp, tid)
Heapify routine for heapsort.
recursive subroutine sink_refi_3x3r_1xr_1xi (size, i, tref, tx, tv, tf, tp, tid)
Sink routine for heapsort.
subroutine swap_refi_3x3r_1xr_1xi (i, j, tref, tx, tv, tf, tp, tid)
Swap routine for heapsort.
subroutine heapsort_refi_3x3r_1xi (n, tref, tx, tv, tf, tid)
Heap sort as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
subroutine heapify_refi_3x3r_1xi (size, n, tref, tx, tv, tf, tid)
Heapify routine for heapsort.
recursive subroutine sink_refi_3x3r_1xi (size, i, tref, tx, tv, tf, tid)
Sink routine for heapsort.
subroutine swap_refi_3x3r_1xi (i, j, tref, tx, tv, tf, tid)
Swap routine for heapsort.
subroutine heapsort_refi_2x3r_1xr_2xi (n, tref, tx, tv, tp, tid, trid)
Heap sort as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
subroutine heapify_refi_2x3r_1xr_2xi (size, n, tref, tx, tv, tp, tid, trid)
Heapify routine for heapsort.
recursive subroutine sink_refi_2x3r_1xr_2xi (size, i, tref, tx, tv, tp, tid, trid)
Sink routine for heapsort.
subroutine swap_refi_2x3r_1xr_2xi (i, j, tref, tx, tv, tp, tid, trid)
Swap routine for heapsort.
subroutine heapsort_refi_2x3r_2xi (n, tref, tx, tv, tid, trid)
Heap sort as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
subroutine heapify_refi_2x3r_2xi (size, n, tref, tx, tv, tid, trid)
Heapify routine for heapsort.
recursive subroutine sink_refi_2x3r_2xi (size, i, tref, tx, tv, tid, trid)
Sink routine for heapsort.
subroutine swap_refi_2x3r_2xi (i, j, tref, tx, tv, tid, trid)
Swap routine for heapsort.
subroutine heapsort_refi_3x3r_1xr_2xi (n, tref, tx, tv, tf, tp, tid, trid)
Heap sort as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
subroutine heapify_refi_3x3r_1xr_2xi (size, n, tref, tx, tv, tf, tp, tid, trid)
Heapify routine for heapsort.
recursive subroutine sink_refi_3x3r_1xr_2xi (size, i, tref, tx, tv, tf, tp, tid, trid)
Sink routine for heapsort.
subroutine swap_refi_3x3r_1xr_2xi (i, j, tref, tx, tv, tf, tp, tid, trid)
Swap routine for heapsort.
subroutine heapsort_refi_3x3r_2xi (n, tref, tx, tv, tf, tid, trid)
Heap sort as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
subroutine heapify_refi_3x3r_2xi (size, n, tref, tx, tv, tf, tid, trid)
Heapify routine for heapsort.
recursive subroutine sink_refi_3x3r_2xi (size, i, tref, tx, tv, tf, tid, trid)
Sink routine for heapsort.
subroutine swap_refi_3x3r_2xi (i, j, tref, tx, tv, tf, tid, trid)
Swap routine for heapsort.
Detailed Description
This module contains sort subroutines.
Authors: F. Roy
Definition at line 8 of file modsortinterf.f90.
Member Function/Subroutine Documentation
subroutine modsortinterf::heapify_refi_2x3r_1xi (integer(kind=4), intent(out) size, integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, integer(kind=pri), dimension(*), intent(inout) tid) private
Heapify routine for heapsort.
Definition at line 701 of file modsortinterf.f90.
References sink_refi_2x3r_1xi().
subroutine modsortinterf::heapify_refi_2x3r_1xr_1xi (integer(kind=4), intent(out) size, integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid) private
Heapify routine for heapsort.
Definition at line 532 of file modsortinterf.f90.
References sink_refi_2x3r_1xr_1xi().
subroutine modsortinterf::heapify_refi_2x3r_1xr_2xi (integer(kind=4), intent(out) size, integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Heapify routine for heapsort.
Definition at line 1211 of file modsortinterf.f90.
References sink_refi_2x3r_1xr_2xi().
subroutine modsortinterf::heapify_refi_2x3r_2xi (integer(kind=4), intent(out) size, integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Heapify routine for heapsort.
Definition at line 1385 of file modsortinterf.f90.
References sink_refi_2x3r_2xi().
subroutine modsortinterf::heapify_refi_3x3r_1xi (integer(kind=4), intent(out) size, integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, integer(kind=pri), dimension(*), intent(inout) tid) private
Heapify routine for heapsort.
Parameters
[in] n length of the arrays
Definition at line 1041 of file modsortinterf.f90.
References sink_refi_3x3r_1xi().
subroutine modsortinterf::heapify_refi_3x3r_1xr_1xi (integer(kind=4), intent(out) size, integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid) private
Heapify routine for heapsort.
Definition at line 864 of file modsortinterf.f90.
References sink_refi_3x3r_1xr_1xi().
subroutine modsortinterf::heapify_refi_3x3r_1xr_2xi (integer(kind=4), intent(out) size, integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Heapify routine for heapsort.
Definition at line 1553 of file modsortinterf.f90.
References sink_refi_3x3r_1xr_2xi().
subroutine modsortinterf::heapify_refi_3x3r_2xi (integer(kind=4), intent(out) size, integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Heapify routine for heapsort.
Definition at line 1735 of file modsortinterf.f90.
References sink_refi_3x3r_2xi().
subroutine modsortinterf::heapsort_refi_2x3r_1xi (integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, integer(kind=pri), dimension(*), intent(inout) tid) private
Heap sort as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
Parameters
[in,out] tx positions array
[in,out] tv velocities array
[in,out] tref halo id array
[in,out] tid particle id array
[in] n length of the arrays
Definition at line 664 of file modsortinterf.f90.
References heapify_refi_2x3r_1xi(), sink_refi_2x3r_1xi(), and swap_refi_2x3r_1xi().
subroutine modsortinterf::heapsort_refi_2x3r_1xr_1xi (integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid) private
Heap sort as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
Parameters
[in,out] tx positions array
[in,out] tv velocities array
[in,out] tp potential array
[in,out] tref halo id array
[in,out] tid particle id array
[in] n length of the arrays
Definition at line 494 of file modsortinterf.f90.
References heapify_refi_2x3r_1xr_1xi(), sink_refi_2x3r_1xr_1xi(), and swap_refi_2x3r_1xr_1xi().
subroutine modsortinterf::heapsort_refi_2x3r_1xr_2xi (integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Heap sort as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
Parameters
[in,out] tx positions array
[in,out] tv velocities array
[in,out] tref halo id array
[in,out] tid particle id array
[in,out] trid ramses particle id array (for cone)
[in,out] tp potential array
[in] n length of the arrays
Definition at line 1172 of file modsortinterf.f90.
References heapify_refi_2x3r_1xr_2xi(), sink_refi_2x3r_1xr_2xi(), and swap_refi_2x3r_1xr_2xi().
subroutine modsortinterf::heapsort_refi_2x3r_2xi (integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Heap sort as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
Parameters
[in,out] tx positions array
[in,out] tv velocities array
[in,out] tref halo id array
[in,out] tid particle id array
[in,out] trid ramses particle id array (for cone)
[in] n length of the arrays
Definition at line 1347 of file modsortinterf.f90.
References heapify_refi_2x3r_2xi(), sink_refi_2x3r_2xi(), and swap_refi_2x3r_2xi().
subroutine modsortinterf::heapsort_refi_3x3r_1xi (integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, integer(kind=pri), dimension(*), intent(inout) tid) private
Heap sort as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
Parameters
[in,out] tx positions array
[in,out] tv velocities array
[in,out] tf gravitational field array
[in,out] tref halo id array
[in,out] tid particle id array
[in] n length of the arrays
Definition at line 1003 of file modsortinterf.f90.
References heapify_refi_3x3r_1xi(), sink_refi_3x3r_1xi(), and swap_refi_3x3r_1xi().
subroutine modsortinterf::heapsort_refi_3x3r_1xr_1xi (integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid) private
Heap sort as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
Parameters
[in,out] tx positions array
[in,out] tv velocities array
[in,out] tref halo id array
[in,out] tid particle id array
[in,out] tf gravitational field array
[in,out] tp potential array
[in] n length of the arrays
Definition at line 825 of file modsortinterf.f90.
References heapify_refi_3x3r_1xr_1xi(), sink_refi_3x3r_1xr_1xi(), and swap_refi_3x3r_1xr_1xi().
subroutine modsortinterf::heapsort_refi_3x3r_1xr_2xi (integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Heap sort as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
Parameters
[in,out] tx positions array
[in,out] tv velocities array
[in,out] tref halo id array
[in,out] tid particle id array
[in,out] trid ramses particle id array (for cone)
[in,out] tp potential array
[in,out] tf gravitational field array
[in] n length of the arrays
Definition at line 1513 of file modsortinterf.f90.
References heapify_refi_3x3r_1xr_2xi(), sink_refi_3x3r_1xr_2xi(), and swap_refi_3x3r_1xr_2xi().
subroutine modsortinterf::heapsort_refi_3x3r_2xi (integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Heap sort as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
Parameters
[in,out] tx positions array
[in,out] tv velocities array
[in,out] tref halo id array
[in,out] tid particle id array
[in,out] trid ramses particle id array (for cone)
[in,out] tf gravitational field array
[in] n length of the arrays
Definition at line 1696 of file modsortinterf.f90.
References heapify_refi_3x3r_2xi(), sink_refi_3x3r_2xi(), and swap_refi_3x3r_2xi().
subroutine modsortinterf::partition_refi_2x3r_1xi (integer(kind=4), intent(in) p, integer(kind=4), intent(in) r, integer(kind=4), intent(out) q, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, integer(kind=pri), dimension(*), intent(inout) tid) private
Partition function for quicksort.
Definition at line 205 of file modsortinterf.f90.
subroutine modsortinterf::partition_refi_2x3r_1xr_1xi (integer(kind=4), intent(in) p, integer(kind=4), intent(in) r, integer(kind=4), intent(out) q, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid) private
Partition function for quicksort.
Definition at line 269 of file modsortinterf.f90.
subroutine modsortinterf::partition_refi_3x3r_1xi (integer(kind=4), intent(in) p, integer(kind=4), intent(in) r, integer(kind=4), intent(out) q, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, integer(kind=pri), dimension(*), intent(inout) tid) private
Partition function for quicksort.
Definition at line 420 of file modsortinterf.f90.
subroutine modsortinterf::partition_refi_3x3r_1xr_1xi (integer(kind=4), intent(in) p, integer(kind=4), intent(in) r, integer(kind=4), intent(out) q, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid) private
Partition function for quicksort.
Definition at line 341 of file modsortinterf.f90.
recursive subroutine modsortinterf::quicksort_refi_2x3r_1xi (integer(kind=4), intent(in) p, integer(kind=4), intent(in) r, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, integer(kind=pri), dimension(*), intent(inout) tid) private
Quicksort algorith as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
Parameters
[in] p index of the first element of the array to be sorted
[in] r index of the last element of the array to be sorted
[in,out] tx positions array
[in,out] tv velocities array
[in,out] tref halo id array
[in,out] tid particle id array
Definition at line 50 of file modsortinterf.f90.
References partition_refi_2x3r_1xi(), and modsortinterf::quicksort::quicksort_refi_2x3r_1xi().
recursive subroutine modsortinterf::quicksort_refi_2x3r_1xr_1xi (integer(kind=4), intent(in) p, integer(kind=4), intent(in) r, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid) private
Quicksort algorith as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
Parameters
[in] p index of the first element of the array to be sorted
[in] r index of the last element of the array to be sorted
[in,out] tx positions array
[in,out] tv velocities array
[in,out] tp potential array
[in,out] tref halo id array
[in,out] tid particle id array
Definition at line 87 of file modsortinterf.f90.
References partition_refi_2x3r_1xr_1xi(), and modsortinterf::quicksort::quicksort_refi_2x3r_1xr_1xi().
recursive subroutine modsortinterf::quicksort_refi_3x3r_1xi (integer(kind=4), intent(in) p, integer(kind=4), intent(in) r, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, integer(kind=pri), dimension(*), intent(inout) tid) private
Quicksort algorith as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
Parameters
[in] p index of the first element of the array to be sorted
[in] r index of the last element of the array to be sorted
[in,out] tx positions array
[in,out] tv velocities array
[in,out] tf potential array
[in,out] tref halo id array
[in,out] tid particle id array
Definition at line 167 of file modsortinterf.f90.
References partition_refi_3x3r_1xi(), and modsortinterf::quicksort::quicksort_refi_3x3r_1xi().
recursive subroutine modsortinterf::quicksort_refi_3x3r_1xr_1xi (integer(kind=4), intent(in) p, integer(kind=4), intent(in) r, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid) private
Quicksort algorith as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
Parameters
[in] p index of the first element of the array to be sorted
[in] r index of the last element of the array to be sorted
[in,out] tx positions array
[in,out] tv velocities array
[in,out] tf gravitational field array
[in,out] tp potential array
[in,out] tref halo id array
[in,out] tid particle id array
Definition at line 127 of file modsortinterf.f90.
References partition_refi_3x3r_1xr_1xi(), and modsortinterf::quicksort::quicksort_refi_3x3r_1xr_1xi().
recursive subroutine modsortinterf::sink_refi_2x3r_1xi (integer(kind=4), intent(in) size, integer(kind=4), intent(in) i, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, integer(kind=pri), dimension(*), intent(inout) tid) private
Sink routine for heapsort.
Definition at line 736 of file modsortinterf.f90.
References swap_refi_2x3r_1xi().
recursive subroutine modsortinterf::sink_refi_2x3r_1xr_1xi (integer(kind=4), intent(in) size, integer(kind=4), intent(in) i, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid) private
Sink routine for heapsort.
Definition at line 568 of file modsortinterf.f90.
References swap_refi_2x3r_1xr_1xi().
recursive subroutine modsortinterf::sink_refi_2x3r_1xr_2xi (integer(kind=4), intent(in) size, integer(kind=4), intent(in) i, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Sink routine for heapsort.
Definition at line 1247 of file modsortinterf.f90.
References swap_refi_2x3r_1xr_2xi().
recursive subroutine modsortinterf::sink_refi_2x3r_2xi (integer(kind=4), intent(in) size, integer(kind=4), intent(in) i, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Sink routine for heapsort.
Definition at line 1420 of file modsortinterf.f90.
References swap_refi_2x3r_2xi().
recursive subroutine modsortinterf::sink_refi_3x3r_1xi (integer(kind=4), intent(in) size, integer(kind=4), intent(in) i, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, integer(kind=pri), dimension(*), intent(inout) tid) private
Sink routine for heapsort.
Definition at line 1077 of file modsortinterf.f90.
References swap_refi_3x3r_1xi().
recursive subroutine modsortinterf::sink_refi_3x3r_1xr_1xi (integer(kind=4), intent(in) size, integer(kind=4), intent(in) i, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid) private
Sink routine for heapsort.
Definition at line 901 of file modsortinterf.f90.
References swap_refi_3x3r_1xr_1xi().
recursive subroutine modsortinterf::sink_refi_3x3r_1xr_2xi (integer(kind=4), intent(in) size, integer(kind=4), intent(in) i, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Sink routine for heapsort.
Definition at line 1590 of file modsortinterf.f90.
References swap_refi_3x3r_1xr_2xi().
recursive subroutine modsortinterf::sink_refi_3x3r_2xi (integer(kind=4), intent(in) size, integer(kind=4), intent(in) i, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Sink routine for heapsort.
Definition at line 1771 of file modsortinterf.f90.
References swap_refi_3x3r_2xi().
subroutine modsortinterf::swap_refi_2x3r_1xi (integer(kind=4), intent(in) i, integer(kind=4), intent(in) j, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, integer(kind=pri), dimension(*), intent(inout) tid) private
Swap routine for heapsort.
Definition at line 781 of file modsortinterf.f90.
subroutine modsortinterf::swap_refi_2x3r_1xr_1xi (integer(kind=4), intent(in) i, integer(kind=4), intent(in) j, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid) private
Swap routine for heapsort.
Definition at line 614 of file modsortinterf.f90.
subroutine modsortinterf::swap_refi_2x3r_1xr_2xi (integer(kind=4), intent(in) i, integer(kind=4), intent(in) j, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Swap routine for heapsort.
Definition at line 1293 of file modsortinterf.f90.
subroutine modsortinterf::swap_refi_2x3r_2xi (integer(kind=4), intent(in) i, integer(kind=4), intent(in) j, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Swap routine for heapsort.
Definition at line 1465 of file modsortinterf.f90.
subroutine modsortinterf::swap_refi_3x3r_1xi (integer(kind=4), intent(in) i, integer(kind=4), intent(in) j, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, integer(kind=pri), dimension(*), intent(inout) tid) private
Swap routine for heapsort.
Definition at line 1123 of file modsortinterf.f90.
subroutine modsortinterf::swap_refi_3x3r_1xr_1xi (integer(kind=4), intent(in) i, integer(kind=4), intent(in) j, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid) private
Swap routine for heapsort.
Definition at line 948 of file modsortinterf.f90.
subroutine modsortinterf::swap_refi_3x3r_1xr_2xi (integer(kind=4), intent(in) i, integer(kind=4), intent(in) j, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Swap routine for heapsort.
Definition at line 1637 of file modsortinterf.f90.
subroutine modsortinterf::swap_refi_3x3r_2xi (integer(kind=4), intent(in) i, integer(kind=4), intent(in) j, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Swap routine for heapsort.
Definition at line 1817 of file modsortinterf.f90.
The documentation for this module was generated from the following file:
/home/roy/Travail/Devel/Cosmologie/Pfof/branches/ModifStruct/common/src/modsortinterf.f90