pFoF: modmap Module Reference
modmap Module Reference
Public Member Functions
subroutine exploremap ()
subroutine map (factor)
subroutine getnpfromshell (factor, if, jf, kf, np)
Public Attributes
integer(kind=4) fofgrid_imin
integer(kind=4) fofgrid_imax
integer(kind=4) fofgrid_jmin
integer(kind=4) fofgrid_jmax
integer(kind=4) fofgrid_kmin
integer(kind=4) fofgrid_kmax
integer(kind=4), dimension(:),
allocatable ict
Detailed Description
Definition at line 5 of file modmap.f90.
Member Function/Subroutine Documentation
subroutine modmap::exploremap ()
Definition at line 20 of file modmap.f90.
References map().
subroutine modmap::getnpfromshell (integer(kind=4), intent(in) factor, integer(kind=4), intent(in) if, integer(kind=4), intent(in) jf, integer(kind=4), intent(in) kf, integer(kind=8), intent(out) np)
Definition at line 339 of file modmap.f90.
subroutine modmap::map (integer(kind=4), intent(in) factor)
Definition at line 53 of file modmap.f90.
References getnpfromshell(), and modio::h5writemap().
Member Data Documentation
integer(kind=4) modmap::fofgrid_imax
Definition at line 11 of file modmap.f90.
integer(kind=4) modmap::fofgrid_imin
Definition at line 11 of file modmap.f90.
integer(kind=4) modmap::fofgrid_jmax
Definition at line 12 of file modmap.f90.
integer(kind=4) modmap::fofgrid_jmin
Definition at line 12 of file modmap.f90.
integer(kind=4) modmap::fofgrid_kmax
Definition at line 13 of file modmap.f90.
integer(kind=4) modmap::fofgrid_kmin
Definition at line 13 of file modmap.f90.
integer(kind=4), dimension(:), allocatable modmap::ict
Definition at line 14 of file modmap.f90.
The documentation for this module was generated from the following file:
/home/roy/Travail/Devel/Cosmologie/Pfof/branches/ModifStruct/tools/conemapper/src/modmap.f90