pFoF: modreadhalo Module Reference
modreadhalo Module Reference
This module contains routines to read HDF5 halo files created with pfof and pfof_cone.
Public Member Functions
subroutine, public h5read_halo_hfprop (filename, common_metadata, parameter_pfof, info_ramses, info_cone, position_halo, velocity_halo, rmax_halo, identity_halo, npart_halo)
Reads a HDF5 halo hfprop file created with pfof.
Detailed Description
This module contains routines to read HDF5 halo files created with pfof and pfof_cone.
Authors: F. Roy
Definition at line 8 of file modreadhalo.f90.
Member Function/Subroutine Documentation
subroutine, public modreadhalo::h5read_halo_hfprop (character(len=400), intent(in) filename, type(type_common_metadata), intent(out) common_metadata, class(type_parameter_pfof), intent(out), optional parameter_pfof, type(type_info_ramses), intent(out), optional info_ramses, type(type_info_cone_part), intent(out), optional info_cone, real(kind=8), dimension(:,:), intent(out), optional, allocatable position_halo, real(kind=8), dimension(:,:), intent(out), optional, allocatable velocity_halo, real(kind=8), dimension(:), intent(out), optional, allocatable rmax_halo, integer(kind=pri), dimension(:), intent(out), optional, allocatable identity_halo, integer(kind=4), dimension(:), intent(out), optional, allocatable npart_halo)
Reads a HDF5 halo hfprop file created with pfof.
Parameters
[in] filename Name of the file
Definition at line 17 of file modreadhalo.f90.
References modiocommons::h5read_meta_info_cone(), modiocommons::h5read_meta_info_ramses(), modiocommons::h5read_meta_pfof_parameter(), modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_open_file(), and modhdf5::hdf5_open_group().
The documentation for this module was generated from the following file:
/home/roy/Travail/Devel/Cosmologie/Pfof/branches/ModifStruct/common/src/modreadhalo.f90