pFoF: modwritecube Module Reference
modwritecube Module Reference
This module contains subroutines used to write HDF5 cubes. Authors: F. Roy.
Public Member Functions
subroutine, public selectwritecubetype ()
subroutine mpih5writesortedcube ()
This subroutine writes the position, the velocity and the id of each particle on the process in a hdf5 file. The particles are gathered.
Public Attributes
procedure(), pointer, public writecube
Private Member Functions
subroutine h5writecube ()
This subroutine writes the position, velocity and id of each particle on the process in a hdf5 file. One file is written per MPI process.
subroutine mpih5writecube ()
This subroutine writes the position, the velocity and the id of each particle on the process in a hdf5 file. The particles are gathered.
subroutine h5writesortedcube ()
Detailed Description
This module contains subroutines used to write HDF5 cubes. Authors: F. Roy.
Definition at line 6 of file modwritecube.f90.
Member Function/Subroutine Documentation
subroutine modwritecube::h5writecube () private
This subroutine writes the position, velocity and id of each particle on the process in a hdf5 file. One file is written per MPI process.
Definition at line 69 of file modwritecube.f90.
References modiocommons::h5write_meta_common(), modiocommons::h5write_meta_info_ramses(), modiocommons::h5write_meta_pfof_parameter(), modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_create_file(), modhdf5::hdf5_create_group(), and modhdf5::hdf5_open_group().
subroutine modwritecube::h5writesortedcube () private
Definition at line 328 of file modwritecube.f90.
References modiocommons::h5write_meta_common(), modiocommons::h5write_meta_info_ramses(), modiocommons::h5write_meta_pfof_parameter(), modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_create_file(), modhdf5::hdf5_create_group(), and modhdf5::hdf5_open_group().
subroutine modwritecube::mpih5writecube () private
This subroutine writes the position, the velocity and the id of each particle on the process in a hdf5 file. The particles are gathered.
Definition at line 186 of file modwritecube.f90.
References modiocommons::h5write_meta_common(), modiocommons::h5write_meta_info_ramses(), modiocommons::h5write_meta_pfof_parameter(), modhdf5::hdf5_close_group(), modhdf5::hdf5_close_mpi_file(), modhdf5::hdf5_create_group(), modhdf5::hdf5_create_mpi_file(), and modhdf5::hdf5_open_group().
subroutine modwritecube::mpih5writesortedcube ()
This subroutine writes the position, the velocity and the id of each particle on the process in a hdf5 file. The particles are gathered.
Definition at line 519 of file modwritecube.f90.
References modiocommons::h5write_meta_common(), modiocommons::h5write_meta_info_ramses(), modiocommons::h5write_meta_pfof_parameter(), modhdf5::hdf5_close_group(), modhdf5::hdf5_close_mpi_file(), modhdf5::hdf5_create_group(), modhdf5::hdf5_create_mpi_file(), and modhdf5::hdf5_open_group().
subroutine, public modwritecube::selectwritecubetype ()
Definition at line 33 of file modwritecube.f90.
References h5writecube(), h5writesortedcube(), mpih5writecube(), and mpih5writesortedcube().
Member Data Documentation
procedure(), pointer, public modwritecube::writecube
Definition at line 19 of file modwritecube.f90.
The documentation for this module was generated from the following file:
/home/roy/Travail/Devel/Cosmologie/Pfof/branches/ModifStruct/pfof_snap/src/modwritecube.f90