pFoF: modio Module Reference
modio Module Reference
This module contains subroutines used for I/O. Authors: F. Roy, V. Bouillot.
Public Member Functions
subroutine, public title ()
subroutine, public readparameters ()
This subroutine reads the input parameters from pfof_snap.nml file (default name) with process 0 and broadcasts them to every processes. It also writes the parameters in a log file and in a backup .nml file.
subroutine, public print_screen_parameters ()
This subroutine writes the input parameters in a .nml file, print them on screen and writes them in the .log file. It should be called only from process 0.
subroutine, public writetimings ()
This subroutine writes timings in the log file and prints them on screen. It should be called only by process 0. It also closes the log file.
subroutine, public ramses_lecture ()
This subroutine reads the particles files created by RAMSES that pFOF has to analyze.
subroutine, public title ()
subroutine, public readparameters ()
This subroutine reads the parameters from the file pfof_cone.nml.
subroutine, public h5readshellinfo ()
This subroutine reads the cone size and the number of particles in each cubic group from each shell file, then writes an index of the cubes found in each shell file.
subroutine, public h5readmap ()
This subroutine reads the map file.
subroutine, public h5readparticles ()
This subroutine reads the particles from the shell files.
subroutine readparameters
subroutine retrievefilelist ()
subroutine readramsesfiles ()
subroutine readconehdr (file, npartloc)
subroutine readconedat (file, ifile)
subroutine h5writecone ()
subroutine readparameters
subroutine retrievefilelist ()
subroutine readramsesfiles ()
subroutine readconegravhdr (file, ncellloc)
subroutine readconegravdat (file, ifile)
subroutine h5writeconegrav ()
subroutine readparameters ()
This subroutine reads the parameters from the file pfof_cone.nml.
subroutine h5readshellinfo ()
This subroutine reads the cone size and the number of particles in each cubic group from each shell file, then perform a reduction to get the total number of particles for each cubic group.
subroutine h5writemap (factor, procNB, dims)
This subroutine writes a map for pfof_cone, this map contains the id of the shell cubes and the procID of the neighbours for each pfof_cone process.
Public Attributes
integer(kind=4) ioerr
integer(kind=4), dimension(:),
allocatable nparttab
integer(kind=4) npartloc
character(len=200), dimension(:),
allocatable filelist
integer(kind=4), dimension(:),
allocatable ncelltab
integer(kind=4), dimension(:,:),
allocatable ncellperleveltab
integer(kind=4) ncellloc
integer(kind=4) nstride
character(len=50) origin
integer(kind=4) first_file
integer(kind=4) last_file
integer ioerr
Detailed Description
This module contains subroutines used for I/O. Authors: F. Roy, V. Bouillot.
This module contains the subroutines and common variables used for I/O in pFoF_cone.
Authors: F. Roy, V. Bouillot
Definition at line 6 of file modio.f90.
Member Function/Subroutine Documentation
subroutine, public modio::h5readmap ()
This subroutine reads the map file.
Definition at line 242 of file modio.f90.
References modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_open_file(), modhdf5::hdf5_open_group(), and modmpicom::settopology().
subroutine, public modio::h5readparticles ()
This subroutine reads the particles from the shell files.
Definition at line 308 of file modio.f90.
References modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_open_file(), and modhdf5::hdf5_open_group().
subroutine, public modio::h5readshellinfo ()
This subroutine reads the cone size and the number of particles in each cubic group from each shell file, then writes an index of the cubes found in each shell file.
Definition at line 109 of file modio.f90.
References modiocommons::h5read_meta_common(), modiocommons::h5read_meta_info_cone(), modiocommons::h5read_meta_info_ramses(), modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_open_file(), and modhdf5::hdf5_open_group().
subroutine modio::h5readshellinfo ()
This subroutine reads the cone size and the number of particles in each cubic group from each shell file, then perform a reduction to get the total number of particles for each cubic group.
Definition at line 45 of file modio.f90.
References modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_open_file(), and modhdf5::hdf5_open_group().
subroutine modio::h5writecone ()
Definition at line 343 of file modio.f90.
References modiocommons::h5write_meta_common(), modiocommons::h5write_meta_conecreator_parameter(), modiocommons::h5write_meta_info_cone(), modiocommons::h5write_meta_info_ramses(), modhdf5::hdf5_close_group(), modhdf5::hdf5_close_mpi_file(), modhdf5::hdf5_create_group(), modhdf5::hdf5_create_mpi_file(), and modhdf5::hdf5_open_group().
subroutine modio::h5writeconegrav ()
Definition at line 342 of file modio.f90.
References modiocommons::h5write_meta_common(), modiocommons::h5write_meta_conecreator_parameter(), modiocommons::h5write_meta_info_cone(), modiocommons::h5write_meta_info_ramses(), modhdf5::hdf5_close_group(), modhdf5::hdf5_close_mpi_file(), modhdf5::hdf5_create_group(), and modhdf5::hdf5_create_mpi_file().
subroutine modio::h5writemap (integer(kind=4), intent(in) factor, integer(kind=4), intent(in) procNB, integer(kind=4), dimension(3), intent(in) dims)
This subroutine writes a map for pfof_cone, this map contains the id of the shell cubes and the procID of the neighbours for each pfof_cone process.
Definition at line 131 of file modio.f90.
References modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_create_file(), and modhdf5::hdf5_create_group().
subroutine, public modio::print_screen_parameters ()
This subroutine writes the input parameters in a .nml file, print them on screen and writes them in the .log file. It should be called only from process 0.
Definition at line 113 of file modio.f90.
subroutine, public modio::ramses_lecture ()
This subroutine reads the particles files created by RAMSES that pFOF has to analyze.
Definition at line 221 of file modio.f90.
References modmpicommons::create_mpi_type_info_ramses(), modmpicommons::emergencystop(), and modreadinfo::readinforamses().
subroutine modio::readconedat (character(len=401), intent(in) file, integer(kind=4), intent(in) ifile)
Definition at line 252 of file modio.f90.
subroutine modio::readconegravdat (character(len=401), intent(in) file, integer(kind=4), intent(in) ifile)
Definition at line 244 of file modio.f90.
subroutine modio::readconegravhdr (character(len=401), intent(in) file, integer(kind=4), intent(out) ncellloc)
Definition at line 218 of file modio.f90.
subroutine modio::readconehdr (character(len=401), intent(in) file, integer(kind=4), intent(out) npartloc)
Definition at line 225 of file modio.f90.
subroutine, public modio::readparameters ()
This subroutine reads the input parameters from pfof_snap.nml file (default name) with process 0 and broadcasts them to every processes. It also writes the parameters in a log file and in a backup .nml file.
Definition at line 65 of file modio.f90.
References modmpicommons::create_mpi_type_param_pfof_snap(), modmpicommons::emergencystop(), and modreadparameters::read_pfof_snap_parameters().
subroutine modio::readparameters ()
Definition at line 30 of file modio.f90.
References modmpicommons::create_mpi_type_param_cone_grav(), and retrievefilelist().
subroutine modio::readparameters ()
Definition at line 24 of file modio.f90.
References modmpicommons::create_mpi_type_param_cone_part(), and retrievefilelist().
subroutine modio::readparameters ()
This subroutine reads the parameters from the file pfof_cone.nml.
Definition at line 18 of file modio.f90.
References modreadparameters::read_pfof_cone_parameters().
subroutine, public modio::readparameters ()
This subroutine reads the parameters from the file pfof_cone.nml.
Definition at line 59 of file modio.f90.
References modmpicommons::create_mpi_type_param_pfof_cone(), modmpicommons::emergencystop(), and modreadparameters::read_pfof_cone_parameters().
subroutine modio::readramsesfiles ()
Definition at line 131 of file modio.f90.
References modmpicommons::create_mpi_type_info_cone_part(), modmpicommons::create_mpi_type_info_ramses(), modmpicommons::emergencystop(), readconegravdat(), readconegravhdr(), modreadinfo::readinfoconegrav(), and modreadinfo::readinforamses().
subroutine modio::readramsesfiles ()
Definition at line 137 of file modio.f90.
References modmpicommons::create_mpi_type_info_cone_part(), modmpicommons::create_mpi_type_info_ramses(), modmpicommons::emergencystop(), readconedat(), readconehdr(), modreadinfo::readinfoconepart(), and modreadinfo::readinforamses().
subroutine modio::retrievefilelist ()
Definition at line 104 of file modio.f90.
subroutine modio::retrievefilelist ()
Definition at line 107 of file modio.f90.
subroutine, public modio::title ()
Definition at line 28 of file modio.f90.
subroutine, public modio::title ()
Definition at line 28 of file modio.f90.
subroutine, public modio::writetimings ()
This subroutine writes timings in the log file and prints them on screen. It should be called only by process 0. It also closes the log file.
Definition at line 163 of file modio.f90.
Member Data Documentation
character(len=200), dimension(:), allocatable modio::filelist
Definition at line 18 of file modio.f90.
integer(kind=4) modio::first_file
Definition at line 23 of file modio.f90.
integer(kind=4) modio::ioerr
Definition at line 18 of file modio.f90.
integer modio::ioerr
Definition at line 12 of file modio.f90.
integer(kind=4) modio::last_file
Definition at line 24 of file modio.f90.
integer(kind=4) modio::ncellloc
Definition at line 17 of file modio.f90.
integer(kind=4), dimension(:,:), allocatable modio::ncellperleveltab
Definition at line 15 of file modio.f90.
integer(kind=4), dimension(:), allocatable modio::ncelltab
Definition at line 14 of file modio.f90.
integer(kind=4) modio::npartloc
Definition at line 16 of file modio.f90.
integer(kind=4), dimension(:), allocatable modio::nparttab
Definition at line 14 of file modio.f90.
integer(kind=4) modio::nstride
Definition at line 18 of file modio.f90.
character(len=50) modio::origin
Definition at line 20 of file modio.f90.
The documentation for this module was generated from the following file:
/home/roy/Travail/Devel/Cosmologie/Pfof/branches/ModifStruct/pfof_snap/src/modio.f90