pFoF: modsortpart Module Reference
modsortpart Module Reference
Public Member Functions
subroutine dividespace ()
subroutine heapsort (n, tref, tx, tv, tf, tp, tid)
subroutine construction (size, n, tref, tx, tv, tf, tp, tid)
recursive subroutine entasser (size, i, tref, tx, tv, tf, tp, tid)
subroutine echanger (i, j, tref, tx, tv, tf, tp, tid)
subroutine dividespace ()
subroutine tritas (n, tref, tx, ta, tp, tr, ti)
subroutine construction (size, n, tref, tx, ta, tp, tr, ti)
recursive subroutine entasser (size, i, tref, tx, ta, tp, tr, ti)
subroutine echanger (i, j, tref, tx, ta, tp, tr, ti)
Detailed Description
Definition at line 6 of file modsortpart.f90.
Member Function/Subroutine Documentation
subroutine modsortpart::construction (integer(kind=4), intent(out) size, integer(kind=4), intent(in) n, integer(kind=4), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real(kind=4), dimension(3,*), intent(inout), optional tf, real(kind=4), dimension(*), intent(inout), optional tp, integer(kind=pri), dimension(*), intent(inout), optional tid)
Definition at line 176 of file modsortpart.f90.
References entasser().
subroutine modsortpart::construction (integer(kind=4), intent(out) size, integer(kind=4), intent(in) n, integer(kind=4), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) ta, real (kind=4), dimension(*), intent(inout) tp, real (kind=4), dimension(*), intent(inout) tr, integer(kind=4), dimension(*), intent(inout) ti)
Definition at line 134 of file modsortpart.f90.
References entasser().
subroutine modsortpart::dividespace ()
Definition at line 18 of file modsortpart.f90.
subroutine modsortpart::dividespace ()
Definition at line 18 of file modsortpart.f90.
subroutine modsortpart::echanger (integer(kind=4), intent(in) i, integer(kind=4), intent(in) j, integer(kind=4), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real(kind=4), dimension(3,*), intent(inout), optional tf, real(kind=4), dimension(*), intent(inout), optional tp, integer(kind=pri), dimension(*), intent(inout), optional tid)
Definition at line 302 of file modsortpart.f90.
subroutine modsortpart::echanger (integer(kind=4), intent(in) i, integer(kind=4), intent(in) j, integer(kind=4), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) ta, real (kind=4), dimension(*), intent(inout) tp, real (kind=4), dimension(*), intent(inout) tr, integer(kind=4), dimension(*), intent(inout) ti)
Definition at line 199 of file modsortpart.f90.
recursive subroutine modsortpart::entasser (integer(kind=4), intent(in) size, integer(kind=4), intent(in) i, integer(kind=4), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real(kind=4), dimension(3,*), intent(inout), optional tf, real(kind=4), dimension(*), intent(inout), optional tp, integer(kind=pri), dimension(*), intent(inout), optional tid)
Definition at line 237 of file modsortpart.f90.
References echanger().
recursive subroutine modsortpart::entasser (integer(kind=4), intent(in) size, integer(kind=4), intent(in) i, integer(kind=4), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) ta, real (kind=4), dimension(*), intent(inout) tp, real (kind=4), dimension(*), intent(inout) tr, integer(kind=4), dimension(*), intent(inout) ti)
Definition at line 161 of file modsortpart.f90.
References echanger(), and entasser().
subroutine modsortpart::heapsort (integer(kind=4), intent(in) n, integer(kind=4), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real(kind=4), dimension(3,*), intent(inout), optional tf, real(kind=4), dimension(*), intent(inout), optional tp, integer(kind=pri), dimension(*), intent(inout), optional tid)
Definition at line 94 of file modsortpart.f90.
References construction(), echanger(), and entasser().
subroutine modsortpart::tritas (integer(kind=4), intent(in) n, integer(kind=4), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) ta, real (kind=4), dimension(*), intent(inout) tp, real (kind=4), dimension(*), intent(inout) tr, integer(kind=4), dimension(*), intent(inout) ti)
Definition at line 107 of file modsortpart.f90.
References construction(), echanger(), and entasser().
The documentation for this module was generated from the following file:
/home/roy/Travail/Devel/Cosmologie/Pfof/branches/ModifStruct/tools/conepartcreator/src/modsortpart.f90