pFoF: modsort Module Reference
modsort Module Reference
This module contains two sort subroutines.
Public Member Functions
recursive subroutine, public trirapide (p, r, tref, tid, tx, tv)
Quick sort as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
subroutine, public tritas (tref, tid, tx, tv, n)
Heap sort as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
subroutine construction (tref, tid, tx, tv, size, n)
Private Member Functions
subroutine partition (tref, p, r, q, tid, tx, tv)
recursive subroutine entasser (tref, tid, tx, tv, size, i)
subroutine echanger (tref, tid, tx, tv, i, j)
Detailed Description
This module contains two sort subroutines.
Authors: F. Roy, V. Bouillot
Definition at line 7 of file modsort.f90.
Member Function/Subroutine Documentation
subroutine modsort::construction (integer(kind=pri), dimension(*), intent(inout) tref, integer(kind=pri), dimension(*), intent(inout) tid, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, integer(kind=4), intent(out) size, integer(kind=4), intent(in) n)
Definition at line 162 of file modsort.f90.
References entasser().
subroutine modsort::echanger (integer(kind=pri), dimension(*), intent(inout) tref, integer(kind=pri), dimension(*), intent(inout) tid, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, integer(kind=4), intent(in) i, integer(kind=4), intent(in) j) private
Definition at line 244 of file modsort.f90.
recursive subroutine modsort::entasser (integer(kind=pri), dimension(*), intent(inout) tref, integer(kind=pri), dimension(*), intent(inout) tid, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, integer(kind=4), intent(in) size, integer(kind=4), intent(in) i) private
Definition at line 198 of file modsort.f90.
References echanger().
subroutine modsort::partition (integer(kind=pri), dimension(*), intent(inout) tref, integer(kind=4), intent(in) p, integer(kind=4), intent(in) r, integer(kind=4), intent(out) q, integer(kind=pri), dimension(*), intent(inout) tid, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv) private
Definition at line 59 of file modsort.f90.
recursive subroutine, public modsort::trirapide (integer(kind=4), intent(in) p, integer(kind=4), intent(in) r, integer(kind=pri), dimension(*), intent(inout) tref, integer(kind=pri), dimension(*), intent(inout) tid, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv)
Quick sort as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
Parameters
[in] p index of the first element of the array to be sorted
[in] r index of the last element of the array to be sorted
[in,out] tx positions array
[in,out] tv velocities array
[in,out] tref halo id array
[in,out] tid particle id array
Definition at line 21 of file modsort.f90.
References partition().
subroutine, public modsort::tritas (integer(kind=pri), dimension(*), intent(inout) tref, integer(kind=pri), dimension(*), intent(inout) tid, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, integer(kind=4), intent(in) n)
Heap sort as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
Definition at line 125 of file modsort.f90.
References construction(), echanger(), and entasser().
The documentation for this module was generated from the following file:
/home/roy/Travail/Devel/Cosmologie/Pfof/trunk/common/src/modsort.f90