pFoF: modiocommons Module Reference
modiocommons Module Reference
Common input/output procedures.
Public Member Functions
subroutine, public h5write_meta_common (file_id, codename, npart)
Write metadata common to every hdf5 ouput files of the pfof toolbox.
subroutine, public h5write_meta_pfof_parameter (file_id, param_pfof)
Write pfof input parameters as metadata.
subroutine, public h5write_meta_conecreator_parameter (file_id, param_cone)
Write conecreator input parameters as metadata.
subroutine, public h5write_meta_info_ramses (file_id, inforamses)
Write ramses info as metadata.
subroutine, public h5write_meta_info_cone (file_id, infocone)
Write light cone info as metadata.
subroutine, public h5read_meta_info_ramses (file_id, inforamses)
Read ramses info as metadata.
subroutine, public h5read_meta_info_cone (file_id, infocone)
Read light cone info as metadata.
subroutine, public h5read_meta_pfof_parameter (file_id, param_pfof)
Read pfof input parameters as metadata.
subroutine, public h5read_meta_conecreator_parameter (file_id, param_cone)
Read conecreator input parameters as metadata.
subroutine, public h5read_meta_common (file_id, common)
Read metadata common to every hdf5 ouput files of the pfof toolbox.
Detailed Description
Common input/output procedures.
Authors: F. Roy
Definition at line 8 of file modiocommons.f90.
Member Function/Subroutine Documentation
subroutine, public modiocommons::h5read_meta_common (integer(kind=hid_t), intent(in) file_id, type(type_common_metadata), intent(out) common)
Read metadata common to every hdf5 ouput files of the pfof toolbox.
Definition at line 1343 of file modiocommons.f90.
References modhdf5::hdf5_close_group(), and modhdf5::hdf5_open_group().
subroutine, public modiocommons::h5read_meta_conecreator_parameter (integer(kind=hid_t), intent(in) file_id, class(type_parameter_conecreator), intent(out) param_cone)
Read conecreator input parameters as metadata.
Definition at line 1245 of file modiocommons.f90.
References modhdf5::hdf5_close_group(), and modhdf5::hdf5_open_group().
subroutine, public modiocommons::h5read_meta_info_cone (integer(kind=hid_t), intent(in) file_id, class(type_info_cone), intent(out) infocone)
Read light cone info as metadata.
Definition at line 918 of file modiocommons.f90.
References modhdf5::hdf5_close_group(), and modhdf5::hdf5_open_group().
subroutine, public modiocommons::h5read_meta_info_ramses (integer(kind=hid_t), intent(in) file_id, type(type_info_ramses), intent(out) inforamses)
Read ramses info as metadata.
Definition at line 839 of file modiocommons.f90.
References modhdf5::hdf5_close_group(), and modhdf5::hdf5_open_group().
subroutine, public modiocommons::h5read_meta_pfof_parameter (integer(kind=hid_t), intent(in) file_id, class(type_parameter_pfof), intent(out) param_pfof)
Read pfof input parameters as metadata.
Definition at line 1073 of file modiocommons.f90.
References modhdf5::hdf5_close_group(), and modhdf5::hdf5_open_group().
subroutine, public modiocommons::h5write_meta_common (integer(kind=hid_t), intent(in) file_id, character(len=h5strlen), intent(in) codename, integer(kind=8), intent(in) npart)
Write metadata common to every hdf5 ouput files of the pfof toolbox.
Definition at line 30 of file modiocommons.f90.
References modhdf5::hdf5_close_group(), and modhdf5::hdf5_open_group().
subroutine, public modiocommons::h5write_meta_conecreator_parameter (integer(kind=hid_t), intent(in) file_id, class(type_parameter_conecreator), intent(in) param_cone)
Write conecreator input parameters as metadata.
Definition at line 279 of file modiocommons.f90.
References modhdf5::hdf5_close_group(), modhdf5::hdf5_create_group(), and modhdf5::hdf5_open_group().
subroutine, public modiocommons::h5write_meta_info_cone (integer(kind=hid_t), intent(in) file_id, class(type_info_cone), intent(in) infocone)
Write light cone info as metadata.
Definition at line 458 of file modiocommons.f90.
References modhdf5::hdf5_close_group(), modhdf5::hdf5_create_group(), and modhdf5::hdf5_open_group().
subroutine, public modiocommons::h5write_meta_info_ramses (integer(kind=hid_t), intent(in) file_id, type(type_info_ramses), intent(in) inforamses)
Write ramses info as metadata.
Definition at line 378 of file modiocommons.f90.
References modhdf5::hdf5_close_group(), modhdf5::hdf5_create_group(), and modhdf5::hdf5_open_group().
subroutine, public modiocommons::h5write_meta_pfof_parameter (integer(kind=hid_t), intent(in) file_id, class(type_parameter_pfof), intent(in) param_pfof)
Write pfof input parameters as metadata.
Definition at line 82 of file modiocommons.f90.
References modhdf5::hdf5_close_group(), modhdf5::hdf5_create_group(), and modhdf5::hdf5_open_group().
The documentation for this module was generated from the following file:
/home/roy/Travail/Devel/Cosmologie/Pfof/branches/ModifStruct/common/src/modiocommons.f90