pFoF: modfofmpi Module Reference
modfofmpi Module Reference
This module contains the initialisation and the communication functions that merge the halo parts of haloes that extend across several processes.
Public Member Functions
subroutine, public mergehaloes (perco2, mpicomm, periodic)
This routine merges haloes that extends across several process by setting their halo ID to the same value.
subroutine initmerging ()
This routine initializes the merging of halo parts. If the flag value is not 0, the position and halo ID of the particle are saved in specific arrays (one array per face).
subroutine findbridge (nloc, nrecv, pos1, pos2, nbridge1, bridge1, nbridge2, bridge2, r2, v1, v2, mpicomm, periodic)
Finds the pairs of particles that should be linked through the merging procedure.
two directions are considered simultaneously by the local process:
1= back 2= front
1= left 2= right
1= bottom 2= top
meaning that the local process exchanges information with the processes located in these two directions.
subroutine setcommonhaloid (mpicomm)
Exchanges the haloID of the particles located near the faces and edges and set the same haloID to each particles that are in the same halo.
Public Attributes
real(kind=4), dimension(:,:),
allocatable posava
real(kind=4), dimension(:,:),
allocatable posarr
real(kind=4), dimension(:,:),
allocatable posbas
real(kind=4), dimension(:,:),
allocatable posdro
real(kind=4), dimension(:,:),
allocatable posgau
real(kind=4), dimension(:,:),
allocatable poshau
integer(kind=pri), dimension(:),
allocatable strava
integer(kind=pri), dimension(:),
allocatable strarr
integer(kind=pri), dimension(:),
allocatable strbas
integer(kind=pri), dimension(:),
allocatable strdro
integer(kind=pri), dimension(:),
allocatable strgau
integer(kind=pri), dimension(:),
allocatable strhau
integer(kind=pri), dimension(:),
allocatable strrec
integer(kind=4) nbridgearr
integer(kind=4) nbridgeava
integer(kind=4) nbridgegau
integer(kind=4) nbridgedro
integer(kind=4) nbridgebas
integer(kind=4) nbridgehau
integer(kind=pri), dimension(:,:),
allocatable bridgearr
integer(kind=pri), dimension(:,:),
allocatable bridgeava
integer(kind=pri), dimension(:,:),
allocatable bridgegau
integer(kind=pri), dimension(:,:),
allocatable bridgedro
integer(kind=pri), dimension(:,:),
allocatable bridgebas
integer(kind=pri), dimension(:,:),
allocatable bridgehau
integer(kind=4), dimension(6) nflagrecv
integer(kind=4), dimension(6),
public nflagloc
integer(kind=1), dimension(:),
allocatable, public border
Detailed Description
This module contains the initialisation and the communication functions that merge the halo parts of haloes that extend across several processes.
Authors: F. Roy, V. Bouillot
Definition at line 9 of file modfofmpi.f90.
Member Function/Subroutine Documentation
subroutine modfofmpi::findbridge (integer(kind=4), dimension(6), intent(in) nloc, integer(kind=4), dimension(6), intent(in) nrecv, real(kind=4), dimension(3,*), intent(in) pos1, real(kind=4), dimension(3,*), intent(in) pos2, integer(kind=4), intent(inout) nbridge1, integer(kind=pri), dimension(:,:), intent(inout), allocatable bridge1, integer(kind=4), intent(inout) nbridge2, integer(kind=pri), dimension(:,:), intent(inout), allocatable bridge2, real(kind=4), intent(in) r2, integer(kind=4), intent(in) v1, integer(kind=4), intent(in) v2, integer, intent(in) mpicomm, logical, intent(in) periodic)
Finds the pairs of particles that should be linked through the merging procedure.
two directions are considered simultaneously by the local process:
1= back 2= front
1= left 2= right
1= bottom 2= top
meaning that the local process exchanges information with the processes located in these two directions.
Parameters
[in] nloc local number of particles flagged for link detection in direction 1
[in] nrecv local number of particles flagged for link detection in direction 2
[in] v1 neighbour index in direction 1
[in] v2 neighbour index in direction 2
[in] pos1 positions of local particles flagged for link detection in direction 1
[in] pos2 positions of distant particles flagged for link detection in direction 2
[in] r2 percolation length
[in] mpicomm MPI communicator used in this subroutine
[in] periodic .true. for standard pFoF and .false. for cone version
[in,out] nbridge1 number of "bridges" found, e.g. pairs of particles that should be linked, in direction 1
[in,out] nbridge2 number of "bridges" found, e.g. pairs of particles that should be linked, in direction 2
[in,out] bridge1 array of indices of the particles forming a bridge in direction 1
[in,out] bridge2 array of indices of the particles forming a bridge in direction 2
Definition at line 184 of file modfofmpi.f90.
subroutine modfofmpi::initmerging ()
This routine initializes the merging of halo parts. If the flag value is not 0, the position and halo ID of the particle are saved in specific arrays (one array per face).
Definition at line 100 of file modfofmpi.f90.
subroutine, public modfofmpi::mergehaloes (real(kind=4), intent(in) perco2, integer, intent(in) mpicomm, logical, intent(in) periodic)
This routine merges haloes that extends across several process by setting their halo ID to the same value.
Parameters
[in] perco2 Value of the percolation length to the square in normalized units (where the box length in equal to 1.0)
[in] mpicomm MPI communicator used in this subroutine
[in] periodic .true. for standard pFoF and .false. for cone version
Definition at line 38 of file modfofmpi.f90.
References findbridge(), initmerging(), and setcommonhaloid().
subroutine modfofmpi::setcommonhaloid (integer, intent(in) mpicomm)
Exchanges the haloID of the particles located near the faces and edges and set the same haloID to each particles that are in the same halo.
Parameters
[in] mpicomm MPI communicator used in this subroutine
Definition at line 326 of file modfofmpi.f90.
Member Data Documentation
integer(kind=1), dimension(:), allocatable, public modfofmpi::border
Definition at line 24 of file modfofmpi.f90.
integer(kind=pri), dimension(:,:), allocatable modfofmpi::bridgearr
Definition at line 20 of file modfofmpi.f90.
integer(kind=pri), dimension(:,:), allocatable modfofmpi::bridgeava
Definition at line 20 of file modfofmpi.f90.
integer(kind=pri), dimension(:,:), allocatable modfofmpi::bridgebas
Definition at line 21 of file modfofmpi.f90.
integer(kind=pri), dimension(:,:), allocatable modfofmpi::bridgedro
Definition at line 21 of file modfofmpi.f90.
integer(kind=pri), dimension(:,:), allocatable modfofmpi::bridgegau
Definition at line 20 of file modfofmpi.f90.
integer(kind=pri), dimension(:,:), allocatable modfofmpi::bridgehau
Definition at line 21 of file modfofmpi.f90.
integer(kind=4) modfofmpi::nbridgearr
Definition at line 18 of file modfofmpi.f90.
integer(kind=4) modfofmpi::nbridgeava
Definition at line 18 of file modfofmpi.f90.
integer(kind=4) modfofmpi::nbridgebas
Definition at line 19 of file modfofmpi.f90.
integer(kind=4) modfofmpi::nbridgedro
Definition at line 19 of file modfofmpi.f90.
integer(kind=4) modfofmpi::nbridgegau
Definition at line 18 of file modfofmpi.f90.
integer(kind=4) modfofmpi::nbridgehau
Definition at line 19 of file modfofmpi.f90.
integer(kind=4), dimension(6), public modfofmpi::nflagloc
Definition at line 23 of file modfofmpi.f90.
integer(kind=4), dimension(6) modfofmpi::nflagrecv
Definition at line 22 of file modfofmpi.f90.
real (kind=4), dimension(:,:), allocatable modfofmpi::posarr
Definition at line 16 of file modfofmpi.f90.
real (kind=4), dimension(:,:), allocatable modfofmpi::posava
Definition at line 16 of file modfofmpi.f90.
real (kind=4), dimension(:,:), allocatable modfofmpi::posbas
Definition at line 16 of file modfofmpi.f90.
real (kind=4), dimension(:,:), allocatable modfofmpi::posdro
Definition at line 16 of file modfofmpi.f90.
real (kind=4), dimension(:,:), allocatable modfofmpi::posgau
Definition at line 16 of file modfofmpi.f90.
real (kind=4), dimension(:,:), allocatable modfofmpi::poshau
Definition at line 16 of file modfofmpi.f90.
integer(kind=pri), dimension(:), allocatable modfofmpi::strarr
Definition at line 17 of file modfofmpi.f90.
integer(kind=pri), dimension(:), allocatable modfofmpi::strava
Definition at line 17 of file modfofmpi.f90.
integer(kind=pri), dimension(:), allocatable modfofmpi::strbas
Definition at line 17 of file modfofmpi.f90.
integer(kind=pri), dimension(:), allocatable modfofmpi::strdro
Definition at line 17 of file modfofmpi.f90.
integer(kind=pri), dimension(:), allocatable modfofmpi::strgau
Definition at line 17 of file modfofmpi.f90.
integer(kind=pri), dimension(:), allocatable modfofmpi::strhau
Definition at line 17 of file modfofmpi.f90.
integer(kind=pri), dimension(:), allocatable modfofmpi::strrec
Definition at line 17 of file modfofmpi.f90.
The documentation for this module was generated from the following file:
/home/roy/Travail/Devel/Cosmologie/Pfof/branches/ModifStruct/common/src/modfofmpi.f90