pFoF: modreadcube Module Reference
modreadcube Module Reference
Public Member Functions
subroutine, public selectreadcubetype ()
subroutine mpih5readsortedcube ()
Public Attributes
procedure(), pointer, public readcube
Private Member Functions
subroutine h5readcube ()
This subroutine reads hdf5 cube files created by pFOF.
subroutine h5readsortedcube ()
This subroutine reads hdf5 sorted cube files created by pFOF.
subroutine mpih5readcube ()
Detailed Description
Definition at line 1 of file modreadcube.f90.
Member Function/Subroutine Documentation
subroutine modreadcube::h5readcube () private
This subroutine reads hdf5 cube files created by pFOF.
Definition at line 65 of file modreadcube.f90.
References modiocommons::h5read_meta_common(), modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_open_file(), and modhdf5::hdf5_open_group().
subroutine modreadcube::h5readsortedcube () private
This subroutine reads hdf5 sorted cube files created by pFOF.
Definition at line 166 of file modreadcube.f90.
References modmpicommons::emergencystop(), modiocommons::h5read_meta_common(), modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_open_file(), and modhdf5::hdf5_open_group().
subroutine modreadcube::mpih5readcube () private
Definition at line 303 of file modreadcube.f90.
References modiocommons::h5read_meta_common(), modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_open_group(), and modhdf5::hdf5_open_mpi_file().
subroutine modreadcube::mpih5readsortedcube ()
Definition at line 451 of file modreadcube.f90.
References modiocommons::h5read_meta_common(), modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_open_file(), and modhdf5::hdf5_open_group().
subroutine, public modreadcube::selectreadcubetype ()
Definition at line 24 of file modreadcube.f90.
References modmpicommons::emergencystop(), h5readcube(), h5readsortedcube(), modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_open_file(), modhdf5::hdf5_open_group(), mpih5readcube(), and mpih5readsortedcube().
Member Data Documentation
procedure(), pointer, public modreadcube::readcube
Definition at line 15 of file modreadcube.f90.
The documentation for this module was generated from the following file:
/home/roy/Travail/Devel/Cosmologie/Pfof/branches/ModifStruct/pfof_snap/src/modreadcube.f90