pFoF: modfofpara Module Reference
modfofpara Module Reference
This module contains the serial FOF algorithm.
Public Member Functions
subroutine fofpara ()
Parallel FOF subroutine Finds haloes on each process then apply the merging process for haloes that extend across several processes.
subroutine init (n, np, ngpp, x, pile, adfirst, npcase, xmin, ymin, zmin, t)
Initialize the stacks of pointers for local friends of friends.
The whole domain is divided into t^3 cubes, where t is the resolution of the simulation analized times the refine_fof factor.
Each process will implicitly considere only its subdomains because every particles treated by the process is located in the same subdomain.
This routine initializes one stack of "pointers" to the index of the particles located in each cube.
subroutine fofparacone ()
Parallel FOF subroutine Finds haloes on each process then apply the merging process for haloes that extend across several processes.
subroutine init (n, np, ngpp, x, pile, adfirst, npcase, xmin, ymin, zmin, t, edgem1)
Initialize the stacks of pointers for local friends of friends.
The whole domain is divided into t^3 cubes, where t is the resolution of the simulation analized times the refine_fof factor.
Each process will implicitly considere only its subdomains because every particles treated by the process is located in the same subdomain.
This routine initializes one stack of "pointers" to the index of the particles located in each cube.
subroutine computeminmax ()
Detailed Description
This module contains the serial FOF algorithm.
Authors: E. Audit, F. Roy, V. Bouillot
Definition at line 8 of file modfofpara.f90.
Member Function/Subroutine Documentation
subroutine modfofpara::computeminmax ()
Definition at line 520 of file modfofpara.f90.
subroutine modfofpara::fofpara ()
Parallel FOF subroutine Finds haloes on each process then apply the merging process for haloes that extend across several processes.
Definition at line 16 of file modfofpara.f90.
References modhalo::computecom(), modhalo::computeradius(), modhalo::gatherhaloes(), modwritehalo::h5writehalopart(), init(), modfofmpi::mergehaloes(), modwritehalo::mpih5writehalomass(), modhalo::selecthaloes(), modsort::tritas(), modio::writehalomass(), and modio::writehalopart().
subroutine modfofpara::fofparacone ()
Parallel FOF subroutine Finds haloes on each process then apply the merging process for haloes that extend across several processes.
Definition at line 17 of file modfofpara.f90.
References modhalo::computecom(), modhalo::computeradius(), modhalo::gatherhaloes(), modwritehalo::h5writehalopart(), init(), modfofmpi::mergehaloes(), modwritehalo::mpih5writehalomass(), modhalo::selecthaloes(), and modsort::tritas().
subroutine modfofpara::init (integer(kind=4), intent(in) n, integer(kind=4), intent(in) np, integer(kind=4), intent(in) ngpp, real(kind=4), dimension(3,np), intent(in) x, integer(kind=4), dimension(np), intent(out) pile, integer(kind=4), dimension(ngpp), intent(out) adfirst, integer(kind=4), dimension(ngpp), intent(out) npcase, real(kind=4) xmin, real(kind=4) ymin, real(kind=4) zmin, real(kind=4), intent(in) t, real(kind=4), intent(in) edgem1)
Initialize the stacks of pointers for local friends of friends.
The whole domain is divided into t^3 cubes, where t is the resolution of the simulation analized times the refine_fof factor.
Each process will implicitly considere only its subdomains because every particles treated by the process is located in the same subdomain.
This routine initializes one stack of "pointers" to the index of the particles located in each cube.
Parameters
[in] n number of "cube" in each dimension in a subdomain, i.e. there are n^3 cubes in a subdomain
[in] np number of particles in the subdomain
[in] ngpp number of "FOF" cubes in the subdomain
[in] x positions of the particles
[in] t resolution of the cosmological simulation times refine_fof factor
[out] npcase number of particles in each cube
[out] adfirst index of the first particle to examine in the cube
[out] pile stack of indices
Definition at line 438 of file modfofpara.f90.
References modmpicom::emergencystop().
subroutine modfofpara::init (integer(kind=4), intent(in) n, integer(kind=4), intent(in) np, integer(kind=4), intent(in) ngpp, real(kind=4), dimension(3,np), intent(in) x, integer(kind=4), dimension(np), intent(out) pile, integer(kind=4), dimension(ngpp), intent(out) adfirst, integer(kind=4), dimension(ngpp), intent(out) npcase, real(kind=4), intent(in) xmin, real(kind=4), intent(in) ymin, real(kind=4), intent(in) zmin, real(kind=4), intent(in) t)
Initialize the stacks of pointers for local friends of friends.
The whole domain is divided into t^3 cubes, where t is the resolution of the simulation analized times the refine_fof factor.
Each process will implicitly considere only its subdomains because every particles treated by the process is located in the same subdomain.
This routine initializes one stack of "pointers" to the index of the particles located in each cube.
Parameters
[in] n number of "cube" in each dimension in a subdomain, i.e. there are n^3 cubes in a subdomain
[in] np number of particles in the subdomain
[in] ngpp number of "FOF" cubes in the subdomain
[in] x positions of the particles
[in] zmin minimum x,y and z of the subdomain
[in] t resolution of the cosmological simulation times refine_fof factor
[out] npcase number of particles in each cube
[out] adfirst index of the first particle to examine in the cube
[out] pile stack of indices
Definition at line 393 of file modfofpara.f90.
References modmpicom::emergencystop().
The documentation for this module was generated from the following file:
/home/roy/Travail/Devel/Cosmologie/Pfof/trunk/pfof_hdf5/src/modfofpara.f90