pFoF: /home/roy/Travail/Devel/Cosmologie/Pfof/trunk/tools/conepartcreator/src/conepartcreator.f90 File Reference
conepartcreator.f90 File Reference
Functions/Subroutines
program conecreator
Function/Subroutine Documentation
program conecreator ()
Definition at line 6 of file conepartcreator.f90.
References modsortpart::dividespace(), modvariables::field, modio::h5writecone(), modhdf5::hdf5_finalize(), modhdf5::hdf5_init(), modsortpart::heapsort(), modvariables::id, modvariables::idcube, modhdf5::mpierr, modvariables::mpistat, modio::npartloc, modio::nparttab, modvariables::pos, modvariables::pot, modvariables::procid, modvariables::procnb, modvariables::ramsespartid, modio::readparameters(), modio::readramsesfiles(), modvariables::req_sumnpc, modio::theend(), and modvariables::vel.