pFoF: /home/roy/Travail/Devel/Cosmologie/Pfof/trunk/tools/conegravcreator/src/conegravcreator.f90 File Reference
conegravcreator.f90 File Reference
Functions/Subroutines
program conegravcreator
Function/Subroutine Documentation
program conegravcreator ()
Definition at line 6 of file conegravcreator.f90.
References modvariable::acc, modsortpart::dividespace(), modio::h5writeconegrav(), modhdf5::hdf5_finalize(), modhdf5::hdf5_init(), modvariable::idcube, modhdf5::mpierr, modvariable::mpistat, modvariable::ncellperlevel, modio::ncelltab, modparam::param, modvariable::phi, modvariable::pos, modvariable::procid, modvariable::procnb, modio::readparameters(), modio::readramsesfiles(), modvariable::refined, modvariable::req_sumnpc, modvariable::rho, modio::theend(), and modsortpart::tritas().