pFoF: modwritehalo Module Reference
modwritehalo Module Reference
This module contains routines to write HDF5 halo files created with pfof and pfof_cone.
Functions/Subroutines
subroutine h5writehalopart (param_pfof, haloNB, halopartNB, haloMass, haloID, halopartPos, halopartVel, halopartID, halopartFor, halopartPot, halopartRamsesID, inforamses, infocone)
This subroutine writes for each halo the position, the velocity and the id of each particle in this halo in a hdf5 file. One file is written per MPI process and several halos per file. There is one group per halo, the name of the group is the ID of the halo.
subroutine mpih5writehalopart (mpicomm, param_pfof, haloNB, halopartNB, haloMass, haloID, halopartPos, halopartVel, halopartID, halopartFor, halopartPot, halopartRamsesID, inforamses, infocone)
This subroutine writes for each halo the position, the velocity and the id of each particle in this halo in a hdf5 file. One file is written per MPI communicator mpicomm and several halos per file, using parallel HDF5. There is one group per halo, the name of the group is the ID of the halo.
subroutine mpih5writehalomass (mpicomm, param_pfof, haloNB_all, haloNB, nh, haloMass, halocomPos, halocomVel, haloID, haloRadius, haloSubHaloNB, inforamses, infocone)
This subroutine writes, for each halo, its mass (number of particles), the position and the velocity of its center of mass and its ID in only one hdf5 file using parallel HDF5.
Detailed Description
This module contains routines to write HDF5 halo files created with pfof and pfof_cone.
Author
Fabrice Roy
Function/Subroutine Documentation
subroutine modwritehalo::h5writehalopart (class(type_parameter_pfof), intent(in) param_pfof, integer(kind=4), intent(in) haloNB, integer(kind=4), intent(in) halopartNB, integer(kind=4), dimension(halonb), intent(in) haloMass, integer(kind=pri), dimension(halonb), intent(in) haloID, real (kind=4), dimension(3,halopartnb), intent(in), target halopartPos, real (kind=4), dimension(3,halopartnb), intent(in), target halopartVel, integer(kind=pri), dimension(halopartnb), intent(in), target halopartID, real (kind=4), dimension(3,halopartnb), intent(in), optional, target halopartFor, real (kind=4), dimension(halopartnb), intent(in), optional, target halopartPot, integer(kind=pri), dimension(halopartnb), intent(in), optional, target halopartRamsesID, type(type_inforamses), intent(in) inforamses, class(type_infocone), intent(in), optional infocone)
This subroutine writes for each halo the position, the velocity and the id of each particle in this halo in a hdf5 file. One file is written per MPI process and several halos per file. There is one group per halo, the name of the group is the ID of the halo.
Parameters
[in] halonb Number of halos
[in] halopartnb Number of particles belonging to the halos
[in] haloid Array containing the ID of the halos
[in] halopartid Array containing the ID of the particles belonging to the halos
[in] halomass Array containing the mass of the halos
[in] halopartvel Array containing the position and velocity of the particles belonging to the halos
[in] halopartpot Array containing the potential of the particles belonging to the halos, this argument is optional
[in] halopartfor Array containing the force on the particles belonging to the halos, this argument is optional
[in] halopartramsesid Array containing the "Ramses" ID of the particles belonging to the halos detected in lightcones
Definition at line 24 of file modwritehalo.f90.
References modiocommons::h5write_meta_common(), modiocommons::h5write_meta_info_cone(), modiocommons::h5write_meta_info_ramses(), modiocommons::h5write_meta_pfof_parameter(), modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_create_file(), modhdf5::hdf5_create_group(), modhdf5::hdf5_open_group(), modmpicom::procid, and modmpicom::procnb.
subroutine modwritehalo::mpih5writehalomass (integer(kind=4), intent(in) mpicomm, class(type_parameter_pfof), intent(in) param_pfof, integer(kind=4), intent(in) haloNB_all, integer(kind=4), intent(in) haloNB, integer(kind=4), intent(in) nh, integer(kind=4), dimension(nh), intent(in), target haloMass, real(kind=8), dimension(3,nh), intent(in), target halocomPos, real(kind=8), dimension(3,nh), intent(in), target halocomVel, integer(kind=pri), dimension(nh), intent(in), target haloID, real(kind=8), dimension(nh), intent(in), target haloRadius, integer(kind=4), dimension(nh), intent(in), target haloSubHaloNB, type(type_inforamses), intent(in) inforamses, class(type_infocone), intent(in), optional infocone)
This subroutine writes, for each halo, its mass (number of particles), the position and the velocity of its center of mass and its ID in only one hdf5 file using parallel HDF5.
Parameters
[in] halonb_all Total number of halos (sum over all processes)
[in] halonb Number of halos
[in] halomass Mass of the halos
[in] halocompos Position of the center of mass of the halos
[in] halocomvel Velocity of the center of mass of the halos
[in] haloid ID of the halos
[in] haloradius Radius of the halos
[in] halosubhalonb Number of subhalos in each halo
[in] mpicomm MPI communicator used to create and write the file
Definition at line 503 of file modwritehalo.f90.
References modiocommons::h5write_meta_common(), modiocommons::h5write_meta_info_cone(), modiocommons::h5write_meta_info_ramses(), modiocommons::h5write_meta_pfof_parameter(), modhdf5::hdf5_create_mpi_file(), modhdf5::hdf5_open_group(), and modmpicom::procid.
subroutine modwritehalo::mpih5writehalopart (integer(kind=4), intent(in) mpicomm, class(type_parameter_pfof), intent(in) param_pfof, integer(kind=4), intent(in) haloNB, integer(kind=4), intent(in) halopartNB, integer(kind=4), dimension(halonb), intent(in) haloMass, integer(kind=pri), dimension(halonb), intent(in) haloID, real (kind=4), dimension(3,halopartnb), intent(in), target halopartPos, real (kind=4), dimension(3,halopartnb), intent(in), target halopartVel, integer(kind=pri), dimension(halopartnb), intent(in), target halopartID, real (kind=4), dimension(3,halopartnb), intent(in), optional, target halopartFor, real (kind=4), dimension(halopartnb), intent(in), optional, target halopartPot, integer(kind=pri), dimension(halopartnb), intent(in), optional, target halopartRamsesID, type(type_inforamses), intent(in) inforamses, class(type_infocone), intent(in), optional infocone)
This subroutine writes for each halo the position, the velocity and the id of each particle in this halo in a hdf5 file. One file is written per MPI communicator mpicomm and several halos per file, using parallel HDF5. There is one group per halo, the name of the group is the ID of the halo.
Parameters
[in] mpicomm MPI communicator used to gather informations
[in] halonb Number of halos
[in] halopartnb Number of particles belonging to the halos
[in] haloid Array containing the ID of the halos
[in] halopartid Array containing the ID of the particles belonging to the halos
[in] halomass Array containing the mass of the halos
[in] halopartvel Array containing the position and velocity of the particles belonging to the halos
[in] halopartpot Array containing the potential of the particles belonging to the halos, this argument is optional
[in] halopartfor Array containing the force on the particles belonging to the halos, this argument is optional
[in] halopartramsesid Array containing the "Ramses" ID of the particles belonging to the halos detected in lightcones
Definition at line 219 of file modwritehalo.f90.
References modmpicom::commcolorwrite, modiocommons::h5write_meta_common(), modiocommons::h5write_meta_info_cone(), modiocommons::h5write_meta_info_ramses(), modiocommons::h5write_meta_pfof_parameter(), modhdf5::hdf5_close_group(), modhdf5::hdf5_close_mpi_file(), modhdf5::hdf5_create_group(), modhdf5::hdf5_create_mpi_file(), modhdf5::hdf5_open_group(), modmpicom::mpierr, modmpicom::procid, and modmpicom::scprocidwrite.