pFoF: modmap Module Reference
modmap Module Reference
Functions/Subroutines
subroutine exploremap ()
subroutine map (factor)
subroutine getnpfromshell (factor, if, jf, kf, np)
Variables
integer(kind=4) fofgrid_imin
integer(kind=4) fofgrid_imax
integer(kind=4) fofgrid_jmin
integer(kind=4) fofgrid_jmax
integer(kind=4) fofgrid_kmin
integer(kind=4) fofgrid_kmax
integer(kind=4), dimension(:), allocatable ict
Function/Subroutine Documentation
subroutine modmap::exploremap ()
Definition at line 21 of file modmap.f90.
References map(), and modvariables::nctab.
subroutine modmap::getnpfromshell (integer(kind=4), intent(in) factor, integer(kind=4), intent(in) if, integer(kind=4), intent(in) jf, integer(kind=4), intent(in) kf, integer(kind=8), intent(out) np)
Definition at line 340 of file modmap.f90.
References fofgrid_imin, fofgrid_jmin, fofgrid_kmin, ict, modvariables::nctab, and modvariables::npartcube.
subroutine modmap::map (integer(kind=4), intent(in) factor)
Definition at line 54 of file modmap.f90.
References modvariables::boundaries, modvariables::cubesize, fofgrid_imax, fofgrid_imin, fofgrid_jmax, fofgrid_jmin, fofgrid_kmax, fofgrid_kmin, modvariables::fullsky, getnpfromshell(), modio::h5writemap(), ict, modvariables::my_npart_tab, modvariables::nctab, modvariables::neigh, modvariables::npart, modvariables::npartcubefof, and modvariables::pictable.
Variable Documentation
integer(kind=4) modmap::fofgrid_imax
Definition at line 11 of file modmap.f90.
integer(kind=4) modmap::fofgrid_imin
Definition at line 11 of file modmap.f90.
integer(kind=4) modmap::fofgrid_jmax
Definition at line 12 of file modmap.f90.
integer(kind=4) modmap::fofgrid_jmin
Definition at line 12 of file modmap.f90.
integer(kind=4) modmap::fofgrid_kmax
Definition at line 13 of file modmap.f90.
integer(kind=4) modmap::fofgrid_kmin
Definition at line 13 of file modmap.f90.
integer(kind=4), dimension(:), allocatable modmap::ict
Definition at line 14 of file modmap.f90.