pFoF: modsortinterf Module Reference
modsortinterf Module Reference
Data Types
interface heapsort
interface quicksort
Functions/Subroutines
recursive subroutine quicksort_refi_2x3r_1xi (p, r, tref, tx, tv, tid)
recursive subroutine quicksort_refi_2x3r_1xr_1xi (p, r, tref, tx, tv, tp, tid)
recursive subroutine quicksort_refi_3x3r_1xr_1xi (p, r, tref, tx, tv, tf, tp, tid)
recursive subroutine quicksort_refi_3x3r_1xi (p, r, tref, tx, tv, tf, tid)
subroutine partition_refi_2x3r_1xi (p, r, q, tref, tx, tv, tid)
subroutine partition_refi_2x3r_1xr_1xi (p, r, q, tref, tx, tv, tp, tid)
subroutine partition_refi_3x3r_1xr_1xi (p, r, q, tref, tx, tv, tf, tp, tid)
subroutine partition_refi_3x3r_1xi (p, r, q, tref, tx, tv, tf, tid)
subroutine heapsort_refi_2x3r_1xr_1xi (n, tref, tx, tv, tp, tid)
Heap sort as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
subroutine construction_refi_2x3r_1xr_1xi (size, n, tref, tx, tv, tp, tid)
recursive subroutine entasser_refi_2x3r_1xr_1xi (size, i, tref, tx, tv, tp, tid)
subroutine echanger_refi_2x3r_1xr_1xi (i, j, tref, tx, tv, tp, tid)
subroutine heapsort_refi_2x3r_1xi (n, tref, tx, tv, tid)
subroutine construction_refi_2x3r_1xi (size, n, tref, tx, tv, tid)
recursive subroutine entasser_refi_2x3r_1xi (size, i, tref, tx, tv, tid)
subroutine echanger_refi_2x3r_1xi (i, j, tref, tx, tv, tid)
subroutine heapsort_refi_3x3r_1xr_1xi (n, tref, tx, tv, tf, tp, tid)
subroutine construction_refi_3x3r_1xr_1xi (size, n, tref, tx, tv, tf, tp, tid)
recursive subroutine entasser_refi_3x3r_1xr_1xi (size, i, tref, tx, tv, tf, tp, tid)
subroutine echanger_refi_3x3r_1xr_1xi (i, j, tref, tx, tv, tf, tp, tid)
subroutine heapsort_refi_3x3r_1xi (n, tref, tx, tv, tf, tid)
subroutine construction_refi_3x3r_1xi (size, n, tref, tx, tv, tf, tid)
recursive subroutine entasser_refi_3x3r_1xi (size, i, tref, tx, tv, tf, tid)
subroutine echanger_refi_3x3r_1xi (i, j, tref, tx, tv, tf, tid)
subroutine heapsort_refi_2x3r_1xr_2xi (n, tref, tx, tv, tp, tid, trid)
subroutine construction_refi_2x3r_1xr_2xi (size, n, tref, tx, tv, tp, tid, trid)
recursive subroutine entasser_refi_2x3r_1xr_2xi (size, i, tref, tx, tv, tp, tid, trid)
subroutine echanger_refi_2x3r_1xr_2xi (i, j, tref, tx, tv, tp, tid, trid)
subroutine heapsort_refi_2x3r_2xi (n, tref, tx, tv, tid, trid)
subroutine construction_refi_2x3r_2xi (size, n, tref, tx, tv, tid, trid)
recursive subroutine entasser_refi_2x3r_2xi (size, i, tref, tx, tv, tid, trid)
subroutine echanger_refi_2x3r_2xi (i, j, tref, tx, tv, tid, trid)
subroutine heapsort_refi_3x3r_1xr_2xi (n, tref, tx, tv, tf, tp, tid, trid)
subroutine construction_refi_3x3r_1xr_2xi (size, n, tref, tx, tv, tf, tp, tid, trid)
recursive subroutine entasser_refi_3x3r_1xr_2xi (size, i, tref, tx, tv, tf, tp, tid, trid)
subroutine echanger_refi_3x3r_1xr_2xi (i, j, tref, tx, tv, tf, tp, tid, trid)
subroutine heapsort_refi_3x3r_2xi (n, tref, tx, tv, tf, tid, trid)
subroutine construction_refi_3x3r_2xi (size, n, tref, tx, tv, tf, tid, trid)
recursive subroutine entasser_refi_3x3r_2xi (size, i, tref, tx, tv, tf, tid, trid)
subroutine echanger_refi_3x3r_2xi (i, j, tref, tx, tv, tf, tid, trid)
Function/Subroutine Documentation
subroutine modsortinterf::construction_refi_2x3r_1xi (integer(kind=4), intent(out) size, integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, integer(kind=pri), dimension(*), intent(inout) tid)
Definition at line 687 of file modsortinterf.f90.
References entasser_refi_2x3r_1xi().
subroutine modsortinterf::construction_refi_2x3r_1xr_1xi (integer(kind=4), intent(out) size, integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid)
Definition at line 517 of file modsortinterf.f90.
References entasser_refi_2x3r_1xr_1xi().
subroutine modsortinterf::construction_refi_2x3r_1xr_2xi (integer(kind=4), intent(out) size, integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid)
Definition at line 1220 of file modsortinterf.f90.
References entasser_refi_2x3r_1xr_2xi().
subroutine modsortinterf::construction_refi_2x3r_2xi (integer(kind=4), intent(out) size, integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid)
Definition at line 1394 of file modsortinterf.f90.
References entasser_refi_2x3r_2xi().
subroutine modsortinterf::construction_refi_3x3r_1xi (integer(kind=4), intent(out) size, integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, integer(kind=pri), dimension(*), intent(inout) tid)
Definition at line 1025 of file modsortinterf.f90.
References entasser_refi_3x3r_1xi().
subroutine modsortinterf::construction_refi_3x3r_1xr_1xi (integer(kind=4), intent(out) size, integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid)
Definition at line 848 of file modsortinterf.f90.
References entasser_refi_3x3r_1xr_1xi().
subroutine modsortinterf::construction_refi_3x3r_1xr_2xi (integer(kind=4), intent(out) size, integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid)
Definition at line 1559 of file modsortinterf.f90.
References entasser_refi_3x3r_1xr_2xi().
subroutine modsortinterf::construction_refi_3x3r_2xi (integer(kind=4), intent(out) size, integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid)
Definition at line 1740 of file modsortinterf.f90.
References entasser_refi_3x3r_2xi().
subroutine modsortinterf::echanger_refi_2x3r_1xi (integer(kind=4), intent(in) i, integer(kind=4), intent(in) j, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, integer(kind=pri), dimension(*), intent(inout) tid) private
Definition at line 767 of file modsortinterf.f90.
subroutine modsortinterf::echanger_refi_2x3r_1xr_1xi (integer(kind=4), intent(in) i, integer(kind=4), intent(in) j, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid) private
Definition at line 601 of file modsortinterf.f90.
subroutine modsortinterf::echanger_refi_2x3r_1xr_2xi (integer(kind=4), intent(in) i, integer(kind=4), intent(in) j, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Definition at line 1304 of file modsortinterf.f90.
subroutine modsortinterf::echanger_refi_2x3r_2xi (integer(kind=4), intent(in) i, integer(kind=4), intent(in) j, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Definition at line 1474 of file modsortinterf.f90.
subroutine modsortinterf::echanger_refi_3x3r_1xi (integer(kind=4), intent(in) i, integer(kind=4), intent(in) j, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, integer(kind=pri), dimension(*), intent(inout) tid) private
Definition at line 1109 of file modsortinterf.f90.
subroutine modsortinterf::echanger_refi_3x3r_1xr_1xi (integer(kind=4), intent(in) i, integer(kind=4), intent(in) j, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid) private
Definition at line 934 of file modsortinterf.f90.
subroutine modsortinterf::echanger_refi_3x3r_1xr_2xi (integer(kind=4), intent(in) i, integer(kind=4), intent(in) j, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Definition at line 1645 of file modsortinterf.f90.
subroutine modsortinterf::echanger_refi_3x3r_2xi (integer(kind=4), intent(in) i, integer(kind=4), intent(in) j, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Definition at line 1824 of file modsortinterf.f90.
recursive subroutine modsortinterf::entasser_refi_2x3r_1xi (integer(kind=4), intent(in) size, integer(kind=4), intent(in) i, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, integer(kind=pri), dimension(*), intent(inout) tid) private
Definition at line 722 of file modsortinterf.f90.
References echanger_refi_2x3r_1xi().
recursive subroutine modsortinterf::entasser_refi_2x3r_1xr_1xi (integer(kind=4), intent(in) size, integer(kind=4), intent(in) i, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid) private
Definition at line 554 of file modsortinterf.f90.
References echanger_refi_2x3r_1xr_1xi().
recursive subroutine modsortinterf::entasser_refi_2x3r_1xr_2xi (integer(kind=4), intent(in) size, integer(kind=4), intent(in) i, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Definition at line 1257 of file modsortinterf.f90.
References echanger_refi_2x3r_1xr_2xi().
recursive subroutine modsortinterf::entasser_refi_2x3r_2xi (integer(kind=4), intent(in) size, integer(kind=4), intent(in) i, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Definition at line 1429 of file modsortinterf.f90.
References echanger_refi_2x3r_2xi().
recursive subroutine modsortinterf::entasser_refi_3x3r_1xi (integer(kind=4), intent(in) size, integer(kind=4), intent(in) i, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, integer(kind=pri), dimension(*), intent(inout) tid) private
Definition at line 1062 of file modsortinterf.f90.
References echanger_refi_3x3r_1xi().
recursive subroutine modsortinterf::entasser_refi_3x3r_1xr_1xi (integer(kind=4), intent(in) size, integer(kind=4), intent(in) i, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid) private
Definition at line 886 of file modsortinterf.f90.
References echanger_refi_3x3r_1xr_1xi().
recursive subroutine modsortinterf::entasser_refi_3x3r_1xr_2xi (integer(kind=4), intent(in) size, integer(kind=4), intent(in) i, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Definition at line 1597 of file modsortinterf.f90.
References echanger_refi_3x3r_1xr_2xi().
recursive subroutine modsortinterf::entasser_refi_3x3r_2xi (integer(kind=4), intent(in) size, integer(kind=4), intent(in) i, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Definition at line 1777 of file modsortinterf.f90.
References echanger_refi_3x3r_2xi().
subroutine modsortinterf::heapsort_refi_2x3r_1xi (integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, integer(kind=pri), dimension(*), intent(inout) tid) private
Definition at line 651 of file modsortinterf.f90.
References construction_refi_2x3r_1xi(), echanger_refi_2x3r_1xi(), and entasser_refi_2x3r_1xi().
subroutine modsortinterf::heapsort_refi_2x3r_1xr_1xi (integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid) private
Heap sort as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
Definition at line 479 of file modsortinterf.f90.
References construction_refi_2x3r_1xr_1xi(), echanger_refi_2x3r_1xr_1xi(), and entasser_refi_2x3r_1xr_1xi().
subroutine modsortinterf::heapsort_refi_2x3r_1xr_2xi (integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Definition at line 1182 of file modsortinterf.f90.
References construction_refi_2x3r_1xr_2xi(), echanger_refi_2x3r_1xr_2xi(), and entasser_refi_2x3r_1xr_2xi().
subroutine modsortinterf::heapsort_refi_2x3r_2xi (integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Definition at line 1358 of file modsortinterf.f90.
References construction_refi_2x3r_2xi(), echanger_refi_2x3r_2xi(), and entasser_refi_2x3r_2xi().
subroutine modsortinterf::heapsort_refi_3x3r_1xi (integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, integer(kind=pri), dimension(*), intent(inout) tid) private
Definition at line 988 of file modsortinterf.f90.
References construction_refi_3x3r_1xi(), echanger_refi_3x3r_1xi(), and entasser_refi_3x3r_1xi().
subroutine modsortinterf::heapsort_refi_3x3r_1xr_1xi (integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid) private
Definition at line 810 of file modsortinterf.f90.
References construction_refi_3x3r_1xr_1xi(), echanger_refi_3x3r_1xr_1xi(), and entasser_refi_3x3r_1xr_1xi().
subroutine modsortinterf::heapsort_refi_3x3r_1xr_2xi (integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Definition at line 1521 of file modsortinterf.f90.
References construction_refi_3x3r_1xr_2xi(), echanger_refi_3x3r_1xr_2xi(), and entasser_refi_3x3r_1xr_2xi().
subroutine modsortinterf::heapsort_refi_3x3r_2xi (integer(kind=4), intent(in) n, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, integer(kind=pri), dimension(*), intent(inout) tid, integer(kind=pri), dimension(*), intent(inout) trid) private
Definition at line 1703 of file modsortinterf.f90.
References construction_refi_3x3r_2xi(), echanger_refi_3x3r_2xi(), and entasser_refi_3x3r_2xi().
subroutine modsortinterf::partition_refi_2x3r_1xi (integer(kind=4), intent(in) p, integer(kind=4), intent(in) r, integer(kind=4), intent(out) q, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, integer(kind=pri), dimension(*), intent(inout) tid) private
Definition at line 192 of file modsortinterf.f90.
subroutine modsortinterf::partition_refi_2x3r_1xr_1xi (integer(kind=4), intent(in) p, integer(kind=4), intent(in) r, integer(kind=4), intent(out) q, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid) private
Definition at line 256 of file modsortinterf.f90.
subroutine modsortinterf::partition_refi_3x3r_1xi (integer(kind=4), intent(in) p, integer(kind=4), intent(in) r, integer(kind=4), intent(out) q, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, integer(kind=pri), dimension(*), intent(inout) tid) private
Definition at line 405 of file modsortinterf.f90.
subroutine modsortinterf::partition_refi_3x3r_1xr_1xi (integer(kind=4), intent(in) p, integer(kind=4), intent(in) r, integer(kind=4), intent(out) q, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid) private
Definition at line 327 of file modsortinterf.f90.
recursive subroutine modsortinterf::quicksort_refi_2x3r_1xi (integer(kind=4), intent(in) p, integer(kind=4), intent(in) r, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, integer(kind=pri), dimension(*), intent(inout) tid) private
Parameters
[in] p index of the first element of the array to be sorted
[in] r index of the last element of the array to be sorted
[in,out] tx positions array
[in,out] tv velocities array
[in,out] tref halo id array
[in,out] tid particle id array
Definition at line 36 of file modsortinterf.f90.
References partition_refi_2x3r_1xi().
recursive subroutine modsortinterf::quicksort_refi_2x3r_1xr_1xi (integer(kind=4), intent(in) p, integer(kind=4), intent(in) r, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid) private
Parameters
[in] p index of the first element of the array to be sorted
[in] r index of the last element of the array to be sorted
[in,out] tx positions array
[in,out] tv velocities array
[in,out] tp potential array
[in,out] tref halo id array
[in,out] tid particle id array
Definition at line 73 of file modsortinterf.f90.
References partition_refi_2x3r_1xr_1xi().
recursive subroutine modsortinterf::quicksort_refi_3x3r_1xi (integer(kind=4), intent(in) p, integer(kind=4), intent(in) r, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, integer(kind=pri), dimension(*), intent(inout) tid) private
Parameters
[in] p index of the first element of the array to be sorted
[in] r index of the last element of the array to be sorted
[in,out] tx positions array
[in,out] tv velocities array
[in,out] tf potential array
[in,out] tref halo id array
[in,out] tid particle id array
Definition at line 153 of file modsortinterf.f90.
References partition_refi_3x3r_1xi().
recursive subroutine modsortinterf::quicksort_refi_3x3r_1xr_1xi (integer(kind=4), intent(in) p, integer(kind=4), intent(in) r, integer(kind=pri), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real (kind=4), dimension(3,*), intent(inout) tf, real (kind=4), dimension(*), intent(inout) tp, integer(kind=pri), dimension(*), intent(inout) tid) private
Parameters
[in] p index of the first element of the array to be sorted
[in] r index of the last element of the array to be sorted
[in,out] tx positions array
[in,out] tv velocities array
[in,out] tf potential array
[in,out] tp potential array
[in,out] tref halo id array
[in,out] tid particle id array
Definition at line 113 of file modsortinterf.f90.
References partition_refi_3x3r_1xr_1xi().