pFoF: modsortpart Module Reference
modsortpart Module Reference
Functions/Subroutines
subroutine dividespace ()
subroutine tritas (n, tref, tx, ta, tp, tr, ti)
subroutine construction (size, n, tref, tx, ta, tp, tr, ti)
recursive subroutine entasser (size, i, tref, tx, ta, tp, tr, ti)
subroutine echanger (i, j, tref, tx, ta, tp, tr, ti)
subroutine heapsort (n, tref, tx, tv, tf, tp, tid)
subroutine construction (size, n, tref, tx, tv, tf, tp, tid)
recursive subroutine entasser (size, i, tref, tx, tv, tf, tp, tid)
subroutine echanger (i, j, tref, tx, tv, tf, tp, tid)
Function/Subroutine Documentation
subroutine modsortpart::construction (integer(kind=4), intent(out) size, integer(kind=4), intent(in) n, integer(kind=4), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) ta, real (kind=4), dimension(*), intent(inout) tp, real (kind=4), dimension(*), intent(inout) tr, integer(kind=4), dimension(*), intent(inout) ti)
Definition at line 135 of file modsortpart.f90.
References entasser().
subroutine modsortpart::construction (integer(kind=4), intent(out) size, integer(kind=4), intent(in) n, integer(kind=4), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real(kind=4), dimension(3,*), intent(inout), optional tf, real(kind=4), dimension(*), intent(inout), optional tp, integer(kind=pri), dimension(*), intent(inout), optional tid)
Definition at line 177 of file modsortpart.f90.
References entasser().
subroutine modsortpart::dividespace ()
Definition at line 19 of file modsortpart.f90.
References modvariable::hy, modvariable::hz, modvariable::idcube, modvariable::infocone, modvariable::mpierr, modvariable::ncellcube, modvariable::ncellcubeloc, modvariable::ncellperlevel, modio::ncube, modvariable::ncx, modvariable::ncy, modvariable::ncz, modparam::param, modvariable::pos, and modvariable::req_sumnpc.
subroutine modsortpart::echanger (integer(kind=4), intent(in) i, integer(kind=4), intent(in) j, integer(kind=4), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) ta, real (kind=4), dimension(*), intent(inout) tp, real (kind=4), dimension(*), intent(inout) tr, integer(kind=4), dimension(*), intent(inout) ti)
Definition at line 200 of file modsortpart.f90.
subroutine modsortpart::echanger (integer(kind=4), intent(in) i, integer(kind=4), intent(in) j, integer(kind=4), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real(kind=4), dimension(3,*), intent(inout), optional tf, real(kind=4), dimension(*), intent(inout), optional tp, integer(kind=pri), dimension(*), intent(inout), optional tid)
Definition at line 303 of file modsortpart.f90.
recursive subroutine modsortpart::entasser (integer(kind=4), intent(in) size, integer(kind=4), intent(in) i, integer(kind=4), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) ta, real (kind=4), dimension(*), intent(inout) tp, real (kind=4), dimension(*), intent(inout) tr, integer(kind=4), dimension(*), intent(inout) ti)
Definition at line 162 of file modsortpart.f90.
References echanger().
recursive subroutine modsortpart::entasser (integer(kind=4), intent(in) size, integer(kind=4), intent(in) i, integer(kind=4), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real(kind=4), dimension(3,*), intent(inout), optional tf, real(kind=4), dimension(*), intent(inout), optional tp, integer(kind=pri), dimension(*), intent(inout), optional tid)
Definition at line 238 of file modsortpart.f90.
References echanger(), and entasser().
subroutine modsortpart::heapsort (integer(kind=4), intent(in) n, integer(kind=4), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) tv, real(kind=4), dimension(3,*), intent(inout), optional tf, real(kind=4), dimension(*), intent(inout), optional tp, integer(kind=pri), dimension(*), intent(inout), optional tid)
Definition at line 95 of file modsortpart.f90.
References construction(), echanger(), and entasser().
subroutine modsortpart::tritas (integer(kind=4), intent(in) n, integer(kind=4), dimension(*), intent(inout) tref, real (kind=4), dimension(3,*), intent(inout) tx, real (kind=4), dimension(3,*), intent(inout) ta, real (kind=4), dimension(*), intent(inout) tp, real (kind=4), dimension(*), intent(inout) tr, integer(kind=4), dimension(*), intent(inout) ti)
Definition at line 108 of file modsortpart.f90.
References construction(), echanger(), and entasser().