pFoF: modiocommons Module Reference
modiocommons Module Reference
Functions/Subroutines
subroutine h5write_meta_common (file_id, codename, npart, process_id)
subroutine h5write_meta_pfof_parameter (file_id, param_pfof)
subroutine h5write_meta_conecreator_parameter (file_id, param_cone)
subroutine h5write_meta_info_ramses (file_id, inforamses, islast)
subroutine h5write_meta_info_cone (file_id, infocone, islast)
subroutine h5readcommonmetadata (file_id, islast, inforamses, infocone)
subroutine h5read_meta_info_ramses (file_id, inforamses, islast)
subroutine h5read_meta_info_cone (file_id, infocone, islast)
subroutine h5read_meta_pfof_parameter (file_id, param_pfof)
subroutine h5read_meta_conecreator_parameter (file_id, param_cone)
Variables
character(len=h5strlen) particle_type = 'dark_matter'
character(len=h5strlen) pfof_cell_order = 'none'
Function/Subroutine Documentation
subroutine modiocommons::h5read_meta_conecreator_parameter (integer(kind=hid_t), intent(in) file_id, class(type_parameter_conecreator), intent(out) param_cone)
Definition at line 1267 of file modiocommons.f90.
References modhdf5::hdf5_close_group(), modhdf5::hdf5_open_group(), modconstant::name_conecreator_grav, and modconstant::name_conecreator_part.
subroutine modiocommons::h5read_meta_info_cone (integer(kind=hid_t), intent(in) file_id, class(type_infocone), intent(out) infocone, logical(kind=4), intent(in) islast)
Definition at line 941 of file modiocommons.f90.
References modhdf5::hdf5_close_group(), and modhdf5::hdf5_open_group().
subroutine modiocommons::h5read_meta_info_ramses (integer(kind=hid_t), intent(in) file_id, type(type_inforamses), intent(out) inforamses, logical(kind=4), intent(in) islast)
Definition at line 855 of file modiocommons.f90.
References modhdf5::hdf5_close_group(), and modhdf5::hdf5_open_group().
subroutine modiocommons::h5read_meta_pfof_parameter (integer(kind=hid_t), intent(in) file_id, class(type_parameter_pfof), intent(out) param_pfof)
Definition at line 1096 of file modiocommons.f90.
References modhdf5::hdf5_close_group(), modhdf5::hdf5_open_group(), modconstant::name_pfof_cone, and modconstant::name_pfof_snap.
subroutine modiocommons::h5readcommonmetadata (integer(kind=hid_t), intent(in) file_id, logical(kind=4), intent(in) islast, type(type_inforamses), intent(out), optional inforamses, class(type_infocone), intent(out), optional infocone)
Definition at line 618 of file modiocommons.f90.
References modhdf5::h5strlen, modhdf5::hdf5_close_group(), modhdf5::hdf5_open_group(), and pfof_cell_order.
subroutine modiocommons::h5write_meta_common (integer(kind=hid_t), intent(in) file_id, character(len=h5strlen), intent(in) codename, integer(kind=8), intent(in) npart, integer(kind=4), intent(in), optional process_id)
Definition at line 15 of file modiocommons.f90.
References modhdf5::hdf5_close_group(), modhdf5::hdf5_open_group(), particle_type, pfof_cell_order, and modconstant::svn_version.
subroutine modiocommons::h5write_meta_conecreator_parameter (integer(kind=hid_t), intent(in) file_id, class(type_parameter_conecreator), intent(in) param_cone)
Definition at line 281 of file modiocommons.f90.
References modhdf5::hdf5_close_group(), modhdf5::hdf5_create_group(), modhdf5::hdf5_open_group(), modconstant::name_conecreator_grav, and modconstant::name_conecreator_part.
subroutine modiocommons::h5write_meta_info_cone (integer(kind=hid_t), intent(in) file_id, class(type_infocone), intent(in) infocone, logical(kind=4), intent(in) islast)
Definition at line 462 of file modiocommons.f90.
References modhdf5::hdf5_close_group(), modhdf5::hdf5_create_group(), and modhdf5::hdf5_open_group().
subroutine modiocommons::h5write_meta_info_ramses (integer(kind=hid_t), intent(in) file_id, type(type_inforamses), intent(in) inforamses, logical(kind=4), intent(in) islast)
Definition at line 379 of file modiocommons.f90.
References modhdf5::hdf5_close_group(), modhdf5::hdf5_create_group(), and modhdf5::hdf5_open_group().
subroutine modiocommons::h5write_meta_pfof_parameter (integer(kind=hid_t), intent(in) file_id, class(type_parameter_pfof), intent(in) param_pfof)
Definition at line 79 of file modiocommons.f90.
References modhdf5::hdf5_close_group(), modhdf5::hdf5_create_group(), modhdf5::hdf5_open_group(), modconstant::name_pfof_cone, and modconstant::name_pfof_snap.
Variable Documentation
character(len=h5strlen) modiocommons::particle_type = 'dark_matter'
Definition at line 8 of file modiocommons.f90.
character(len=h5strlen) modiocommons::pfof_cell_order = 'none'
Definition at line 9 of file modiocommons.f90.