pFoF: modfofpara Module Reference
modfofpara Module Reference
Contains the serial FOF algorithm.
Functions/Subroutines
subroutine fofpara ()
Serial FOF subroutine.
subroutine init (n, np, ngpp, x, pile, adfirst, npcase, xmin, ymin, zmin, t)
Initializes the stacks of pointers for local friends of friends.
subroutine fofparacone ()
Parallel FOF subroutine Finds haloes on each process then apply the merging process for haloes that extend across several processes.
subroutine init (n, np, ngpp, x, pile, adfirst, npcase, xmin, ymin, zmin, t, edgem1)
Initialize the stacks of pointers for local friends of friends.
The whole domain is divided into t^3 cubes, where t is the resolution of the simulation analized times the refine_fof factor.
Each process will implicitly considere only its subdomains because every particles treated by the process is located in the same subdomain.
This routine initializes one stack of "pointers" to the index of the particles located in each cube.
subroutine computeminmax ()
Detailed Description
Contains the serial FOF algorithm.
This module contains the serial FOF algorithm.
Authors: E. Audit, F. Roy, V. Bouillot
Function/Subroutine Documentation
subroutine modfofpara::computeminmax ()
Definition at line 635 of file modfofpara.f90.
References modmpicom::mpierr, modvariables::partmax, modvariables::partmin, and modvariables::pos.
subroutine modfofpara::fofpara ()
Serial FOF subroutine.
Halo detection is performed locally in each subdomains (by each process).
Structures which are cut by a border between two subdomains are gathered.
The criterium to gather two parts of a halo is simple: if one particle in a halo is seperated from a particle in another halo (on the other side of a border) by a distance smaller than the percolation parameter, then these two halos are two parts of a single halo.
Definition at line 32 of file modfofpara.f90.
References modfofmpi::border, modhalo::computecom(), modhalo::computeradius(), modmpicom::dims, modvariables::forf, modhalo::gatherhaloes(), modwritehalo::h5writehalopart(), modhalo::halocompos, modhalo::halocomvel, modhalo::haloid, modhalo::halomass, modhalo::halonb, modhalo::halonb_all, modhalo::halopartfor, modhalo::halopartid, modhalo::halopartnb, modhalo::halopartpos, modhalo::halopartpot, modhalo::halopartvel, modhalo::haloradius, modhalo::halosubhalonb, modvariables::id, modvariables::idf, modvariables::inforamses, init(), modfofmpi::mergehaloes(), modmpicom::mpicube, modmpicom::mpierr, modwritehalo::mpih5writehalomass(), modwritehalo::mpih5writehalopart(), modmpicom::mpisubcubewrite, modhalo::myfinalnpart, modvariables::mynpart, modfofmpi::nflagloc, modvariables::nres, modparameters::param, modvariables::pos, modvariables::posf, modvariables::potf, modmpicom::procid, modhalo::selecthaloes(), modvariables::stf, modvariables::structure, modtiming::tfofinit, modtiming::tfofloc, modtiming::tgatherhalo, modtiming::time0, modtiming::timeint, modtiming::tobs, modtiming::touthalopart, modtiming::toutmass, modtiming::traccord, modtiming::tselecthalo, modtiming::tsort, modvariables::velf, modvariables::xmax, modvariables::xmin, modvariables::ymax, modvariables::ymin, modvariables::zmax, and modvariables::zmin.
subroutine modfofpara::fofparacone ()
Parallel FOF subroutine Finds haloes on each process then apply the merging process for haloes that extend across several processes.
Definition at line 18 of file modfofpara.f90.
References modfofmpi::border, modmpicom::commgatherwrite, modhalo::computecom(), modhalo::computeradius(), modvariables::forf, modhalo::gatherhaloes(), modwritehalo::h5writehalopart(), modhalo::halocompos, modhalo::halocomvel, modhalo::haloid, modhalo::halomass, modhalo::halonb, modhalo::halonb_all, modhalo::halopartfor, modhalo::halopartid, modhalo::halopartnb, modhalo::halopartpos, modhalo::halopartpot, modhalo::halopartramsesid, modhalo::halopartvel, modhalo::haloradius, modhalo::halosubhalonb, modvariables::id, modvariables::idf, modvariables::infocone, modvariables::infoconelast, modvariables::inforamses, modvariables::inforamseslast, init(), modfofmpi::mergehaloes(), modmpicom::mpierr, modwritehalo::mpih5writehalomass(), modwritehalo::mpih5writehalopart(), modhalo::myfinalnpart, modvariables::mynpart, modfofmpi::nflagloc, modvariables::nres, modparameters::param, modvariables::pos, modvariables::posf, modvariables::potf, modmpicom::procid, modmpicom::procnb, modvariables::ramsesidf, modhalo::selecthaloes(), modvariables::stf, modvariables::structure, modtiming::tfof, modtiming::tfofinit, modtiming::time0, modtiming::timeint, modtiming::tobs, modtiming::tout, modtiming::traccord, and modvariables::velf.
subroutine modfofpara::init (integer(kind=4), intent(in) n, integer(kind=4), intent(in) np, integer(kind=4), intent(in) ngpp, real(kind=4), dimension(3,np), intent(in) x, integer(kind=4), dimension(np), intent(out) pile, integer(kind=4), dimension(ngpp), intent(out) adfirst, integer(kind=4), dimension(ngpp), intent(out) npcase, real(kind=4), intent(in) xmin, real(kind=4), intent(in) ymin, real(kind=4), intent(in) zmin, real(kind=4), intent(in) t)
Initializes the stacks of pointers for local friends of friends.
The whole domain is divided into t^3 cubes, where t is the resolution of the simulation analized times the refine_fof factor.
Each process will implicitly considere only its subdomains because every particles treated by the process is located in the same subdomain.
This routine initializes one stack of "pointers" to the index of the particles located in each cube.
Parameters
[in] n number of "cubes" in each dimension in a subdomain, i.e. there are n^3 cubes in a subdomain
[in] np number of particles in the subdomain
[in] ngpp number of "FOF" cubes in the subdomain
[in] x positions of the particles
[in] zmin minimum x,y and z of the subdomain
[in] t resolution of the cosmological simulation times refine_fof factor
[out] npcase number of particles in each cube
[out] adfirst index of the first particle to examine in the cube
[out] pile stack of indices
Definition at line 479 of file modfofpara.f90.
References modmpicom::emergencystop().
subroutine modfofpara::init (integer(kind=4), intent(in) n, integer(kind=4), intent(in) np, integer(kind=4), intent(in) ngpp, real(kind=4), dimension(3,np), intent(in) x, integer(kind=4), dimension(np), intent(out) pile, integer(kind=4), dimension(ngpp), intent(out) adfirst, integer(kind=4), dimension(ngpp), intent(out) npcase, real(kind=4) xmin, real(kind=4) ymin, real(kind=4) zmin, real(kind=4), intent(in) t, real(kind=4), intent(in) edgem1)
Initialize the stacks of pointers for local friends of friends.
The whole domain is divided into t^3 cubes, where t is the resolution of the simulation analized times the refine_fof factor.
Each process will implicitly considere only its subdomains because every particles treated by the process is located in the same subdomain.
This routine initializes one stack of "pointers" to the index of the particles located in each cube.
Parameters
[in] n number of "cube" in each dimension in a subdomain, i.e. there are n^3 cubes in a subdomain
[in] np number of particles in the subdomain
[in] ngpp number of "FOF" cubes in the subdomain
[in] x positions of the particles
[in] t resolution of the cosmological simulation times refine_fof factor
[out] npcase number of particles in each cube
[out] adfirst index of the first particle to examine in the cube
[out] pile stack of indices
Definition at line 553 of file modfofpara.f90.
References modmpicom::emergencystop().