pFoF: modwritecube Module Reference
modwritecube Module Reference
This module contains subroutines used to write HDF5 cubes.
Functions/Subroutines
subroutine h5writecube ()
This subroutine writes the position, velocity and id of each particle on the process in a hdf5 file. One file is written per MPI process.
subroutine mpih5writecube ()
This subroutine writes the position, the velocity and the id of each particle on the process in a hdf5 file. The particles are gathered.
subroutine h5writesortedcube ()
subroutine mpih5writesortedcube ()
This subroutine writes the position, the velocity and the id of each particle on the process in a hdf5 file. The particles are gathered.
Detailed Description
This module contains subroutines used to write HDF5 cubes.
Function/Subroutine Documentation
subroutine modwritecube::h5writecube ()
This subroutine writes the position, velocity and id of each particle on the process in a hdf5 file. One file is written per MPI process.
Parameters
Definition at line 30 of file modwritecube.f90.
References modvariables::for, modiocommons::h5write_meta_common(), modiocommons::h5write_meta_info_ramses(), modiocommons::h5write_meta_pfof_parameter(), modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_create_file(), modhdf5::hdf5_create_group(), modhdf5::hdf5_open_group(), modvariables::id, modvariables::inforamses, modmpicom::mpicube, modmpicom::mpierr, modvariables::mynpart, modparameters::param, modvariables::pos, modvariables::pot, modmpicom::procid, modmpicom::procnb, modvariables::vel, modvariables::xmax, modvariables::xmin, modvariables::ymax, modvariables::ymin, modvariables::zmax, and modvariables::zmin.
subroutine modwritecube::h5writesortedcube ()
Definition at line 292 of file modwritecube.f90.
References modmpicom::dims, modvariables::for, modiocommons::h5write_meta_common(), modiocommons::h5write_meta_info_ramses(), modiocommons::h5write_meta_pfof_parameter(), modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_create_file(), modhdf5::hdf5_create_group(), modhdf5::hdf5_open_group(), modvariables::id, modvariables::inforamses, modvariables::mynpart, modparameters::param, modvariables::pos, modvariables::pot, modmpicom::procid, modmpicom::procnb, modvariables::vel, modvariables::xmax, modvariables::xmin, modvariables::ymax, modvariables::ymin, modvariables::zmax, and modvariables::zmin.
subroutine modwritecube::mpih5writecube ()
This subroutine writes the position, the velocity and the id of each particle on the process in a hdf5 file. The particles are gathered.
Definition at line 148 of file modwritecube.f90.
References modmpicom::commcolorwrite, modvariables::for, modiocommons::h5write_meta_common(), modiocommons::h5write_meta_info_ramses(), modiocommons::h5write_meta_pfof_parameter(), modhdf5::hdf5_close_group(), modhdf5::hdf5_close_mpi_file(), modhdf5::hdf5_create_group(), modhdf5::hdf5_create_mpi_file(), modhdf5::hdf5_open_group(), modvariables::id, modvariables::inforamses, modmpicom::mpierr, modmpicom::mpisubcubewrite, modvariables::mynpart, modparameters::param, modvariables::pos, modvariables::pot, modmpicom::procid, modmpicom::procnb, modvariables::vel, modvariables::xmax, modvariables::xmin, modvariables::ymax, modvariables::ymin, modvariables::zmax, and modvariables::zmin.
subroutine modwritecube::mpih5writesortedcube ()
This subroutine writes the position, the velocity and the id of each particle on the process in a hdf5 file. The particles are gathered.
Definition at line 484 of file modwritecube.f90.
References modmpicom::commcolorwrite, modmpicom::dims, modvariables::for, modiocommons::h5write_meta_common(), modiocommons::h5write_meta_info_ramses(), modiocommons::h5write_meta_pfof_parameter(), modhdf5::hdf5_close_group(), modhdf5::hdf5_close_mpi_file(), modhdf5::hdf5_create_group(), modhdf5::hdf5_create_mpi_file(), modhdf5::hdf5_open_group(), modvariables::id, modvariables::inforamses, modmpicom::mpierr, modmpicom::mpisubcubewrite, modvariables::mynpart, modparameters::param, modvariables::pos, modvariables::pot, modmpicom::procid, modmpicom::procnb, modmpicom::scprocidwrite, modvariables::vel, modvariables::xmax, modvariables::xmin, modvariables::ymax, modvariables::ymin, modvariables::zmax, and modvariables::zmin.