pFoF: modio Module Reference
modio Module Reference
This module contains subroutines used for I/O.
Functions/Subroutines
subroutine title ()
subroutine theend ()
subroutine readparameters ()
This subroutine reads the input parameters from pfof_snap.nml file (default name) with process 0 and broadcasts them to every processes. It also writes the parameters in a log file and in a backup .nml file.
subroutine print_screen_parameters ()
This subroutine writes the input parameters in a .nml file, print them on screen and writes them in the .log file. It should be called only from process 0.
subroutine writetimings ()
This subroutine writes timings in the log file and prints them on screen. It should be called only by process 0. It also closes the log file.
subroutine ramses_lecture ()
This subroutine reads the particles files created by RAMSES that pFOF has to analyze.
subroutine h5readshellinfo ()
This subroutine reads the cone size and the number of particles in each cubic group from each shell file, then writes an index of the cubes found in each shell file.
subroutine h5readmap ()
This subroutine reads the map file.
subroutine h5readparticles ()
This subroutine reads the particles from the shell files.
subroutine retrievefilelist ()
subroutine readramsesfiles ()
subroutine readconegravhdr (file, ncellloc)
subroutine readconegravdat (file, ifile)
subroutine h5writeconegrav ()
subroutine h5writemap (factor, procNB, dims, coords)
This subroutine writes a map for pfof_cone, this map contains the id of the shell cubes and the procID of the neighbours for each pfof_cone process.
subroutine readconehdr (file, npartloc)
subroutine readconedat (file, ifile)
subroutine h5writecone ()
Variables
integer(kind=4) ncube
integer(kind=4) ioerr
integer(kind=4), dimension(:), allocatable npart_tab
integer(kind=4), dimension(:), allocatable ncelltab
integer(kind=4), dimension(:,:), allocatable ncellperleveltab
integer(kind=4) ncellloc
integer(kind=4) nstride
character(len=50) origin
integer(kind=4) first_file
integer(kind=4) last_file
integer(kind=4), dimension(:), allocatable nparttab
integer(kind=4) npartloc
character(len=200), dimension(:), allocatable filelist
Detailed Description
This module contains subroutines used for I/O.
This module contains the subroutines and common variables used for I/O in pFoF_cone.
Authors: F. Roy, V. Bouillot
Function/Subroutine Documentation
subroutine modio::h5readmap ()
This subroutine reads the map file.
Definition at line 332 of file modio.f90.
References modvariables::boundaries, modmpicom::cubecoord, modmpicom::dims, modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_open_file(), modhdf5::hdf5_open_group(), modvariables::ictable, modmpicom::mpierr, modvariables::mynpart, modmpicom::neighbours, npart_tab, modmpicom::procid, modmpicom::procnb, modmpicom::settopology(), and modvariables::shellcubes_size.
subroutine modio::h5readparticles ()
This subroutine reads the particles from the shell files.
Definition at line 408 of file modio.f90.
References modvariables::cubepershell, modvariables::for, modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_open_file(), modhdf5::hdf5_open_group(), modvariables::ictable, modvariables::id, modvariables::indexcube, modvariables::mynpart, ncube, modvariables::npart, npart_tab, modparameters::param, modvariables::pos, modvariables::pot, modmpicom::procid, modmpicom::procnb, modvariables::ramsesid, modvariables::shell_nb, modvariables::shellcubes_size, and modvariables::vel.
subroutine modio::h5readshellinfo ()
This subroutine reads the cone size and the number of particles in each cubic group from each shell file, then writes an index of the cubes found in each shell file.
This subroutine reads the cone size and the number of particles in each cubic group from each shell file, then perform a reduction to get the total number of particles for each cubic group.
Definition at line 177 of file modio.f90.
References modvariables::cubepershell, modiocommons::h5readcommonmetadata(), modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_open_file(), modhdf5::hdf5_open_group(), modvariables::ictable, modvariables::indexcube, modvariables::infocone, modvariables::infoconelast, modvariables::inforamses, modvariables::inforamseslast, modmpicommons::mpi_type_infocone_part, modmpicommons::mpi_type_inforamses, modmpicom::mpierr, ncube, modvariables::nres, modparameters::param, modmpicom::procid, modmpicom::procnb, modvariables::shell_nb, and modvariables::shellcubes_size.
subroutine modio::h5writecone ()
Definition at line 343 of file modio.f90.
References modiocommons::h5write_meta_common(), modiocommons::h5write_meta_conecreator_parameter(), modiocommons::h5write_meta_info_cone(), modiocommons::h5write_meta_info_ramses(), modhdf5::hdf5_create_mpi_file(), modhdf5::hdf5_open_group(), modvariables::infocone, modvariables::inforamses, ncube, modparameters::param, modvariables::procid, and modvariables::procnb.
subroutine modio::h5writeconegrav ()
Definition at line 335 of file modio.f90.
References modiocommons::h5write_meta_common(), modiocommons::h5write_meta_conecreator_parameter(), modiocommons::h5write_meta_info_cone(), modiocommons::h5write_meta_info_ramses(), modhdf5::hdf5_create_mpi_file(), modhdf5::hdf5_open_group(), modvariable::infocone, modvariable::inforamses, ncube, modparam::param, modvariable::procid, and modvariable::procnb.
subroutine modio::h5writemap (integer(kind=4), intent(in) factor, integer(kind=4), intent(in) procNB, integer(kind=4), dimension(3), intent(in) dims, integer(kind=4), dimension(3,procnb), intent(in) coords)
This subroutine writes a map for pfof_cone, this map contains the id of the shell cubes and the procID of the neighbours for each pfof_cone process.
Definition at line 136 of file modio.f90.
References modvariables::boundaries, modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_create_file(), modhdf5::hdf5_create_group(), modvariables::my_npart_tab, modvariables::neigh, and modvariables::pictable.
subroutine modio::print_screen_parameters ()
This subroutine writes the input parameters in a .nml file, print them on screen and writes them in the .log file. It should be called only from process 0.
Definition at line 203 of file modio.f90.
References modparameters::param, and modmpicom::procid.
subroutine modio::ramses_lecture ()
This subroutine reads the particles files created by RAMSES that pFOF has to analyze.
Definition at line 309 of file modio.f90.
References modmpicom::cubecoord, modmpicom::emergencystop(), modvariables::for, modvariables::id, modvariables::inforamses, modconstant::mpi_pri, modmpicom::mpicube, modmpicom::mpierr, modmpicom::mpireqr1, modmpicom::mpireqr2, modmpicom::mpireqr3, modmpicom::mpireqr4, modmpicom::mpireqr5, modmpicom::mpireqs1, modmpicom::mpireqs2, modmpicom::mpireqs3, modmpicom::mpireqs4, modmpicom::mpireqs5, modvariables::mynpart, modvariables::ngrid, modvariables::npart, modvariables::nres, modparameters::param, modvariables::pos, modvariables::pot, modmpicom::procid, modmpicom::procnb, modreadinfo::readinforamses(), modtiming::time0, modtiming::timeint, modtiming::tinitread, modtiming::tread, modtiming::treadfile, modtiming::ttailpart, modconstant::ulog, modvariables::vel, modvariables::xmax, modvariables::xmin, modvariables::ymax, modvariables::ymin, modvariables::zmax, and modvariables::zmin.
subroutine modio::readconedat (character(len=401), intent(in) file, integer(kind=4), intent(in) ifile)
Definition at line 245 of file modio.f90.
References modvariables::field, modvariables::infocone, modvariables::inforamses, ioerr, nparttab, modparameters::param, modvariables::pos, modvariables::pot, modvariables::ramsespartid, and modvariables::vel.
subroutine modio::readconegravdat (character(len=401), intent(in) file, integer(kind=4), intent(in) ifile)
Definition at line 237 of file modio.f90.
References modvariable::acc, first_file, ioerr, modvariable::ncellperlevel, ncellperleveltab, nstride, modparam::param, modvariable::phi, modvariable::pos, modvariable::procid, modvariable::refined, and modvariable::rho.
subroutine modio::readconegravhdr (character(len=401), intent(in) file, integer(kind=4), intent(out) ncellloc)
Definition at line 211 of file modio.f90.
References ioerr, modvariable::ncellperlevel, and nstride.
subroutine modio::readconehdr (character(len=401), intent(in) file, integer(kind=4), intent(out) npartloc)
Definition at line 218 of file modio.f90.
References modvariables::infocone, and ioerr.
subroutine modio::readparameters ()
This subroutine reads the input parameters from pfof_snap.nml file (default name) with process 0 and broadcasts them to every processes. It also writes the parameters in a log file and in a backup .nml file.
This subroutine reads the parameters from the file pfof_cone.nml.
Definition at line 72 of file modio.f90.
References modmpicommons::create_mpi_type_info(), modmpicommons::mpi_type_parameter_pfof_snap, modmpicom::mpierr, modparameters::param, modmpicom::procid, modmpicom::procnb, modconstant::ulog, and modconstant::uopa.
subroutine modio::readramsesfiles ()
Definition at line 144 of file modio.f90.
References modvariable::acc, modvariable::filelist, first_file, modvariable::infocone, modvariable::inforamses, last_file, ncellloc, modvariable::ncellperlevel, ncellperleveltab, ncelltab, modparam::param, modvariable::phi, modvariable::pos, modvariable::procid, readconegravdat(), readconegravhdr(), modreadinfo::readinfoconegrav(), modreadinfo::readinforamses(), modvariable::refined, and modvariable::rho.
subroutine modio::retrievefilelist ()
Definition at line 117 of file modio.f90.
References modvariable::filelist, and modparam::param.
subroutine modio::theend ()
Definition at line 58 of file modio.f90.
subroutine modio::title ()
Definition at line 25 of file modio.f90.
References modmpicom::procnb.
subroutine modio::writetimings ()
This subroutine writes timings in the log file and prints them on screen. It should be called only by process 0. It also closes the log file.
Definition at line 252 of file modio.f90.
References modtiming::tfof, modtiming::tfofinit, modtiming::tfofloc, modtiming::tgatherhalo, modtiming::tinitread, modtiming::tobs, modtiming::tout, modtiming::touthalopart, modtiming::toutmass, modtiming::traccord, modtiming::tread, modtiming::treadfile, modtiming::tselecthalo, modtiming::tsort, modtiming::ttailpart, and modconstant::ulog.
Variable Documentation
character(len=200), dimension(:), allocatable modio::filelist
Definition at line 18 of file modio.f90.
integer(kind=4) modio::first_file
Definition at line 23 of file modio.f90.
integer modio::ioerr
Definition at line 17 of file modio.f90.
integer(kind=4) modio::last_file
Definition at line 24 of file modio.f90.
integer(kind=4) modio::ncellloc
Definition at line 17 of file modio.f90.
integer(kind=4), dimension(:,:), allocatable modio::ncellperleveltab
Definition at line 15 of file modio.f90.
integer(kind=4), dimension(:), allocatable modio::ncelltab
Definition at line 14 of file modio.f90.
integer(kind=4) modio::ncube
Definition at line 16 of file modio.f90.
integer(kind=4), dimension(:), allocatable modio::npart_tab
Definition at line 18 of file modio.f90.
integer(kind=4) modio::npartloc
Definition at line 16 of file modio.f90.
integer(kind=4), dimension(:), allocatable modio::nparttab
Definition at line 14 of file modio.f90.
integer(kind=4) modio::nstride
Definition at line 18 of file modio.f90.
character(len=50) modio::origin
Definition at line 20 of file modio.f90.