pFoF: modextract Module Reference
modextract Module Reference
Functions/Subroutines
subroutine extract_cuboid ()
recursive subroutine quicksort (p, r, tab)
Quick sort as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
subroutine partition (p, r, q, tab)
Variables
real(kind=4), dimension(3) center
character(len=8) type
real(kind=4), dimension(3) dimensions
character(len=400) filename
logical(kind=4) potential = .false.
logical(kind=4) force = .false.
Function/Subroutine Documentation
subroutine modextract::extract_cuboid ()
Definition at line 23 of file modextract.f90.
References center, dimensions, filename, modvariables::for, force, modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_finalize(), modhdf5::hdf5_init(), modhdf5::hdf5_open_file(), modhdf5::hdf5_open_group(), modvariables::id, modvariables::pos, modvariables::pot, potential, quicksort(), and modvariables::vel.
subroutine modextract::partition (integer(kind=4), intent(in) p, integer(kind=4), intent(in) r, integer(kind=4), intent(out) q, integer(kind=4), dimension(2,*), intent(inout) tab)
Definition at line 304 of file modextract.f90.
recursive subroutine modextract::quicksort (integer(kind=4), intent(in) p, integer(kind=4), intent(in) r, integer(kind=4), dimension(2,*), intent(inout) tab)
Quick sort as described in Introduction to algorithms (Cormen, Leiserson, Rivest, Stein)
Parameters
[in] p index of the first element of the array to be sorted
[in] r index of the last element of the array to be sorted
[in,out] tab array
Definition at line 269 of file modextract.f90.
References partition().
Variable Documentation
real(kind=4), dimension(3) modextract::center
Definition at line 12 of file modextract.f90.
real(kind=4), dimension(3) modextract::dimensions
Definition at line 14 of file modextract.f90.
character(len=400) modextract::filename
Definition at line 15 of file modextract.f90.
logical(kind=4) modextract::force = .false.
Definition at line 17 of file modextract.f90.
logical(kind=4) modextract::potential = .false.
Definition at line 16 of file modextract.f90.
character(len=8) modextract::type
Definition at line 13 of file modextract.f90.