pFoF: modanalyzeengines Module Reference
modanalyzeengines Module Reference
Data Types
interface generic_function
type listofvar
Functions/Subroutines
subroutine analyzelist (halolistfilename, myfunction, inputvarlist)
Analyze a list of haloes defined in the file halolistfilename Apply the function generic_function to each halo individually.
subroutine analyzefile (halofilename, myfunction, inputvarlist)
Analyze each halo contained in the halo file halofilename Apply the function generic_function to each halo individually.
Function/Subroutine Documentation
subroutine modanalyzeengines::analyzefile (character(len=400), intent(in) halofilename, procedure(generic_function) myfunction, type(listofvar), intent(in), optional inputvarlist)
Analyze each halo contained in the halo file halofilename Apply the function generic_function to each halo individually.
Definition at line 217 of file modanalyzeengines.f90.
References modvariable::currenthalo, modvariable::currenthaloid, modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_open_file(), modhdf5::hdf5_open_group(), modvariable::id, modvariable::mp, modhdf5::mpierr, modvariable::nbhaloanalyzed, modvariable::pos, modvariable::procid, modvariable::procnb, and modvariable::vel.
subroutine modanalyzeengines::analyzelist (character(len=400), intent(in) halolistfilename, procedure(generic_function) myfunction, type(listofvar), intent(in), optional inputvarlist)
Analyze a list of haloes defined in the file halolistfilename Apply the function generic_function to each halo individually.
Definition at line 32 of file modanalyzeengines.f90.
References modvariable::currenthalo, modvariable::currenthaloid, modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_open_file(), modhdf5::hdf5_open_group(), modvariable::id, modvariable::mp, modvariable::mpi_pri, modhdf5::mpierr, modvariable::nbhaloanalyzed, modvariable::pos, modvariable::procid, modvariable::procnb, and modvariable::vel.