pFoF: modreadcube Module Reference
modreadcube Module Reference
Functions/Subroutines
subroutine selectcubetype ()
Opens a cube file, reads the file_type metadata, and selects the corresponding reading subroutine. Sets the readcube procedure pointer to the right subroutine.
subroutine h5readcube ()
Reads a standard hdf5 cube file created by pfof_snap.
subroutine h5readsortedcube ()
Reads a hdf5 sorted cube file created by pfof_snap.
subroutine mpih5readcube ()
Reads a parallel HDF5 cube file created by pfof_snap.
subroutine mpih5readsortedcube ()
Reads a parallel and sorted HDF5 cube file created by pfof_snap.
Variables
procedure(), pointer readcube
Procedure pointer pointing to the cube reading subroutine selected from the "file_type" metadata in the HDF5 cube file.
Function/Subroutine Documentation
subroutine modreadcube::h5readcube ()
Reads a standard hdf5 cube file created by pfof_snap.
Definition at line 79 of file modreadcube.f90.
References modvariables::for, modiocommons::h5readcommonmetadata(), modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_open_file(), modhdf5::hdf5_open_group(), modvariables::id, modvariables::inforamses, modvariables::mynpart, modvariables::ngrid, modvariables::npart, modvariables::nres, modparameters::param, modvariables::pos, modvariables::pot, modmpicom::procid, modvariables::vel, modvariables::xmax, modvariables::xmin, modvariables::ymax, modvariables::ymin, modvariables::zmax, and modvariables::zmin.
subroutine modreadcube::h5readsortedcube ()
Reads a hdf5 sorted cube file created by pfof_snap.
Definition at line 181 of file modreadcube.f90.
References modmpicom::emergencystop(), modvariables::for, modiocommons::h5readcommonmetadata(), modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_open_file(), modhdf5::hdf5_open_group(), modvariables::id, modvariables::inforamses, modvariables::mynpart, modvariables::ngrid, modvariables::npart, modvariables::nres, modparameters::param, modvariables::pos, modvariables::pot, modmpicom::procid, modvariables::vel, modvariables::xmax, modvariables::xmin, modvariables::ymax, modvariables::ymin, modvariables::zmax, and modvariables::zmin.
subroutine modreadcube::mpih5readcube ()
Reads a parallel HDF5 cube file created by pfof_snap.
Definition at line 320 of file modreadcube.f90.
References modmpicom::commcolorread, modvariables::for, modiocommons::h5readcommonmetadata(), modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_open_group(), modhdf5::hdf5_open_mpi_file(), modvariables::id, modvariables::inforamses, modmpicom::mpierr, modmpicom::mpisubcuberead, modvariables::mynpart, modvariables::ngrid, modvariables::npart, modvariables::nres, modparameters::param, modvariables::pos, modvariables::pot, modmpicom::procid, modmpicom::scprocidread, modvariables::vel, modvariables::xmax, modvariables::xmin, modvariables::ymax, modvariables::ymin, modvariables::zmax, and modvariables::zmin.
subroutine modreadcube::mpih5readsortedcube ()
Reads a parallel and sorted HDF5 cube file created by pfof_snap.
Definition at line 465 of file modreadcube.f90.
References modmpicom::commcolorread, modvariables::for, modiocommons::h5readcommonmetadata(), modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_open_file(), modhdf5::hdf5_open_group(), modvariables::id, modvariables::inforamses, modmpicom::mpierr, modvariables::mynpart, modvariables::ngrid, modvariables::npart, modvariables::nres, modparameters::param, modvariables::pos, modvariables::pot, modmpicom::procid, modmpicom::scprocidread, modvariables::vel, modvariables::xmax, modvariables::xmin, modvariables::ymax, modvariables::ymin, modvariables::zmax, and modvariables::zmin.
subroutine modreadcube::selectcubetype ()
Opens a cube file, reads the file_type metadata, and selects the corresponding reading subroutine. Sets the readcube procedure pointer to the right subroutine.
Definition at line 38 of file modreadcube.f90.
References modmpicom::emergencystop(), h5readcube(), h5readsortedcube(), modhdf5::hdf5_close_file(), modhdf5::hdf5_close_group(), modhdf5::hdf5_open_file(), modhdf5::hdf5_open_group(), modmpicom::mpierr, mpih5readcube(), mpih5readsortedcube(), modparameters::param, modmpicom::procid, and readcube.
Variable Documentation
procedure(), pointer modreadcube::readcube
Procedure pointer pointing to the cube reading subroutine selected from the "file_type" metadata in the HDF5 cube file.
Definition at line 29 of file modreadcube.f90.