pFoF: /home/roy/Travail/Devel/Cosmologie/Pfof/trunk/pfof_snap/src/pfof_snap.f90 File Reference
pfof_snap.f90 File Reference
Functions/Subroutines
program friend
Detailed Description
Author
Fabrice Roy
Vincent Bouillot
This file contains the main program.
Definition in file pfof_snap.f90.
Function/Subroutine Documentation
program friend ()
Definition at line 71 of file pfof_snap.f90.
References modfofpara::fofpara(), modwritecube::h5writecube(), modwritecube::h5writesortedcube(), modhdf5::hdf5_finalize(), modhdf5::hdf5_init(), modmpicom::mpierr, modwritecube::mpih5writecube(), modwritecube::mpih5writesortedcube(), modvariables::ngrid, modvariables::nres, modparameters::param, modio::print_screen_parameters(), modmpicom::procid, modmpicom::procnb, modio::ramses_lecture(), modreadcube::readcube, modio::readparameters(), modreadcube::selectcubetype(), modmpicom::setcommunicators(), modtiming::tfof, modtiming::tfofinit, modtiming::tfofloc, modio::theend(), modtiming::timeint, modio::title(), modtiming::tobs, modtiming::tout, modtiming::traccord, modtiming::tread, modtiming::treadfile, and modio::writetimings().