pFoF: /home/roy/Travail/Devel/Cosmologie/Pfof/trunk/pfof_cone/src/pfof_cone.f90 File Reference
pfof_cone.f90 File Reference
Functions/Subroutines
program pfof_cone
pFOF_cone is a distributed implementation of the Friends-of-Friends halo finder algorithm designed for lightcones simulated with RAMSES.
This parallel Friend of Friend implementation is based on a sequential implementation written by Edouard Audit (CEA).
It has been written by Fabrice Roy – CNRS / LUTH (Observatoire de Paris) and Vincent Bouillot.
mail: fabri.nosp@m.ce.r.nosp@m.oy@ob.nosp@m.spm..nosp@m.fr
mail: vince.nosp@m.nt.b.nosp@m.ouill.nosp@m.ot@o.nosp@m.bspm..nosp@m.fr
Function/Subroutine Documentation
program pfof_cone ()
pFOF_cone is a distributed implementation of the Friends-of-Friends halo finder algorithm designed for lightcones simulated with RAMSES.
This parallel Friend of Friend implementation is based on a sequential implementation written by Edouard Audit (CEA).
It has been written by Fabrice Roy – CNRS / LUTH (Observatoire de Paris) and Vincent Bouillot.
mail: fabri.nosp@m.ce.r.nosp@m.oy@ob.nosp@m.spm..nosp@m.fr
mail: vince.nosp@m.nt.b.nosp@m.ouill.nosp@m.ot@o.nosp@m.bspm..nosp@m.fr
Definition at line 8 of file pfof_cone.f90.
References modfofpara::computeminmax(), modvariables::deallocall(), modfofpara::fofparacone(), modio::h5readmap(), modio::h5readparticles(), modio::h5readshellinfo(), modhdf5::hdf5_finalize(), modhdf5::hdf5_init(), modmpicom::mpierr, modmpicom::procid, modmpicom::procnb, modio::readparameters(), modio::theend(), and modio::title().