pFoF: /home/roy/Travail/Devel/Cosmologie/Pfof/trunk/tools/conepartcreator/src/testshell.f90 File Reference
testshell.f90 File Reference
Functions/Subroutines
program testshell
subroutine writeramsestext
subroutine readwritehdf5
Function/Subroutine Documentation
subroutine readwritehdf5 ()
Definition at line 59 of file testshell.f90.
References modhdf5::hdf5_close_group(), modhdf5::hdf5_open_file(), modhdf5::hdf5_open_group(), modvariable::pos, and modvariable::vel.
program testshell ()
Definition at line 1 of file testshell.f90.
References modhdf5::hdf5_finalize(), modhdf5::hdf5_init(), modvariable::id, modhdf5::mpierr, modio::nparttab, modvariable::pos, modvariable::procid, modvariable::procnb, modio::readparameters(), modio::readramsesfiles(), readwritehdf5(), modvariable::vel, and writeramsestext().
subroutine writeramsestext ()
Definition at line 37 of file testshell.f90.
References modio::npartloc, modvariable::pos, modvariable::procid, and modvariable::vel.